"""Persistence model.

Conventions applied to every business table:

* ``id`` is a UUID generated by the application, stable across environments.
* Tenant-owned rows carry ``organization_id`` and every uniqueness constraint
  that could collide between tenants includes it.
* ``created_at`` / ``updated_at`` are UTC and set by the application, not by the
  database, so behaviour is identical on SQLite and PostgreSQL.
* Deletion is logical (``deleted_at``) for anything a user can reference from an
  estimate; audit rows are never deleted.
"""

from __future__ import annotations

import uuid
from datetime import UTC, date, datetime
from decimal import Decimal

from sqlalchemy import JSON as SAJSON
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .db import Amount, Base


def new_id() -> str:
    return str(uuid.uuid4())


def utcnow() -> datetime:
    return datetime.now(UTC).replace(tzinfo=None)


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=utcnow, onupdate=utcnow, nullable=False
    )


# --------------------------------------------------------------------------
# Identity, organisations, permissions
# --------------------------------------------------------------------------


class Organization(TimestampMixin, Base):
    __tablename__ = "organizations"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    legal_name: Mapped[str | None] = mapped_column(String(200))
    company_number: Mapped[str | None] = mapped_column(String(50))
    country_code: Mapped[str] = mapped_column(String(2), nullable=False, default="BE")
    region_code: Mapped[str] = mapped_column(String(10), nullable=False, default="BE-WAL")
    locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    timezone: Mapped[str] = mapped_column(String(50), nullable=False, default="Europe/Brussels")
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)

    settings: Mapped[OrganizationSettings] = relationship(
        back_populates="organization", uselist=False, cascade="all, delete-orphan"
    )


class OrganizationSettings(TimestampMixin, Base):
    """Company rules that drive the deterministic engine.

    These values are copied into a frozen estimate version; changing them later
    never rewrites a frozen figure.
    """

    __tablename__ = "organization_settings"

    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), primary_key=True
    )
    rounding_scale: Mapped[int] = mapped_column(Integer, nullable=False, default=2)
    rounding_mode: Mapped[str] = mapped_column(String(20), nullable=False, default="half_up")
    unit_price_scale: Mapped[int] = mapped_column(Integer, nullable=False, default=2)

    site_overheads_rate: Mapped[Decimal] = mapped_column(
        Amount, nullable=False, default=Decimal("0")
    )
    site_overheads_base: Mapped[str] = mapped_column(
        String(30), nullable=False, default="direct_cost"
    )
    general_overheads_rate: Mapped[Decimal] = mapped_column(
        Amount, nullable=False, default=Decimal("0")
    )
    general_overheads_base: Mapped[str] = mapped_column(
        String(30), nullable=False, default="direct_plus_site"
    )
    contingency_rate: Mapped[Decimal] = mapped_column(Amount, nullable=False, default=Decimal("0"))
    contingency_base: Mapped[str] = mapped_column(
        String(30), nullable=False, default="running_total"
    )
    margin_rate: Mapped[Decimal] = mapped_column(Amount, nullable=False, default=Decimal("0"))
    margin_method: Mapped[str] = mapped_column(String(20), nullable=False, default="on_cost")

    missing_price_policy: Mapped[str] = mapped_column(String(10), nullable=False, default="block")
    quote_number_pattern: Mapped[str] = mapped_column(
        String(60), nullable=False, default="DEV-{year}-{sequence:04d}"
    )
    show_internal_costs_in_client_pdf: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )
    ai_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    organization: Mapped[Organization] = relationship(back_populates="settings")


class TaxRateRow(TimestampMixin, Base):
    __tablename__ = "tax_rates"
    __table_args__ = (
        UniqueConstraint("organization_id", "code", "applies_from", name="uq_tax_org_code_from"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    code: Mapped[str] = mapped_column(String(30), nullable=False)
    label: Mapped[str] = mapped_column(String(120), nullable=False)
    rate: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    applies_from: Mapped[datetime | None] = mapped_column(Date)
    applies_to: Mapped[datetime | None] = mapped_column(Date)
    is_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    source: Mapped[str | None] = mapped_column(String(255))


class User(TimestampMixin, Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    full_name: Mapped[str] = mapped_column(String(200), nullable=False)
    locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    memberships: Mapped[list[Membership]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class ExternalIdentity(TimestampMixin, Base):
    """Le lien entre un compte local et une identité chez un fournisseur.

    La clé est le couple ``(issuer, subject)``, que le fournisseur garantit
    immuable. L'adresse électronique ne sert qu'une fois, à créer ce lien : elle
    est réattribuable et usurpable, et s'y fier durablement permettrait de
    reprendre un compte en obtenant l'adresse chez le fournisseur.

    ``email_at_link`` conserve l'adresse telle qu'elle était au moment de la
    liaison. Elle ne sert à rien d'autre qu'à retrouver plus tard *pourquoi*
    ce lien existe — un audit, pas une identification.

    Un utilisateur peut porter plusieurs identités (deux fournisseurs), mais une
    identité donnée n'appartient qu'à un utilisateur : l'unicité porte sur
    ``(issuer, subject)``.
    """

    __tablename__ = "external_identities"
    __table_args__ = (
        UniqueConstraint("issuer", "subject", name="uq_external_identity_issuer_subject"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    issuer: Mapped[str] = mapped_column(String(255), nullable=False)
    subject: Mapped[str] = mapped_column(String(255), nullable=False)
    email_at_link: Mapped[str | None] = mapped_column(String(255))
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime)


class LoginTransaction(Base):
    """Une demande de connexion en cours, du départ au retour du navigateur.

    Elle vit en base et non en mémoire de processus : l'utilisateur peut partir
    depuis une instance de l'API et revenir sur une autre, qui ne connaîtrait
    rien d'un dictionnaire local. C'est la condition pour tourner à plus d'une
    instance.

    ``consumed_at`` fait du rejeu un refus par l'état, pas par une convention :
    une transaction déjà servie ne peut plus l'être, quelle que soit la
    fenêtre de temps restante.

    ``login_code`` est le code opaque rendu au navigateur à la place du jeton.
    Un JWT dans une URL de retour finit dans l'historique, les journaux du
    proxy et l'en-tête ``Referer`` ; un code court, à usage unique et échangé
    contre la session, non.
    """

    __tablename__ = "login_transactions"
    __table_args__ = (
        UniqueConstraint("state", name="uq_login_transaction_state"),
        UniqueConstraint("login_code", name="uq_login_transaction_code"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    state: Mapped[str] = mapped_column(String(64), nullable=False)
    nonce: Mapped[str] = mapped_column(String(64), nullable=False)
    code_verifier: Mapped[str] = mapped_column(String(128), nullable=False)
    redirect_uri: Mapped[str] = mapped_column(String(500), nullable=False)
    #: Où renvoyer l'utilisateur dans l'application après la connexion.
    return_to: Mapped[str | None] = mapped_column(String(500))
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    #: Horodatage de la consommation du `state`, au retour du fournisseur.
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime)
    #: Rempli une fois l'identité vérifiée, puis effacé à l'échange.
    login_code: Mapped[str | None] = mapped_column(String(64))
    login_code_expires_at: Mapped[datetime | None] = mapped_column(DateTime)
    user_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    organization_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("organizations.id"))


class Membership(TimestampMixin, Base):
    """A user's role inside one organisation. A user may belong to several."""

    __tablename__ = "memberships"
    __table_args__ = (
        UniqueConstraint("user_id", "organization_id", name="uq_membership_user_org"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(String(40), nullable=False, default="estimator")
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    user: Mapped[User] = relationship(back_populates="memberships")


# --------------------------------------------------------------------------
# Country / region packs
# --------------------------------------------------------------------------


class RegionProfile(TimestampMixin, Base):
    """A versioned country/region pack.

    Global (not tenant-owned): the pack describes public rules, an organisation
    only *selects* one. ``terminology`` and ``rules`` stay JSON on purpose —
    what a pack needs to declare differs per country and must not require a
    migration for each new one.
    """

    __tablename__ = "region_profiles"
    __table_args__ = (UniqueConstraint("code", "version", name="uq_region_code_version"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    country_code: Mapped[str] = mapped_column(String(2), nullable=False, index=True)
    code: Mapped[str] = mapped_column(String(10), nullable=False)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    version: Mapped[str] = mapped_column(String(20), nullable=False, default="2026.1")
    effective_from: Mapped[datetime | None] = mapped_column(Date)
    default_locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    locales: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    default_currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    terminology: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    rules: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    sources: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    disclaimer: Mapped[str | None] = mapped_column(Text)


# --------------------------------------------------------------------------
# Projects
# --------------------------------------------------------------------------


class Project(TimestampMixin, Base):
    __tablename__ = "projects"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        ForeignKeyConstraint(
            ["client_id", "organization_id"],
            ["clients.id", "clients.organization_id"],
            name="fk_projects_client_tenant",
        ),
        UniqueConstraint("id", "organization_id", name="uq_projects_id_organization"),
        UniqueConstraint("organization_id", "reference", name="uq_project_org_reference"),
        Index("ix_projects_org_status", "organization_id", "status"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    reference: Mapped[str] = mapped_column(String(60), nullable=False)
    client_reference: Mapped[str | None] = mapped_column(String(120))
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    #: La fiche client choisie pour ce chantier. Facultative : les projets
    #: antérieurs au répertoire n'en ont pas, et doivent rester lisibles.
    #: `client_name` et `client_reference` restent ce qu'ils étaient — la
    #: mémoire de ce qui avait été saisi avant.
    client_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("clients.id"))
    client_name: Mapped[str | None] = mapped_column(String(200))
    address: Mapped[str | None] = mapped_column(String(255))
    postal_code: Mapped[str | None] = mapped_column(String(20))
    city: Mapped[str | None] = mapped_column(String(120))
    country_code: Mapped[str] = mapped_column(String(2), nullable=False, default="BE")
    region_code: Mapped[str] = mapped_column(String(10), nullable=False, default="BE-WAL")
    latitude: Mapped[Decimal | None] = mapped_column(Amount)
    longitude: Mapped[Decimal | None] = mapped_column(Amount)
    market_type: Mapped[str | None] = mapped_column(String(60))
    work_categories: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    submission_deadline: Mapped[datetime | None] = mapped_column(DateTime)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="draft")
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class Client(TimestampMixin, Base):
    """Le destinataire commercial d'un devis, réutilisable d'un chantier à l'autre.

    Jusqu'ici, « le client » n'existait que comme deux chaînes libres portées
    par le projet : `client_name` et `client_reference`. Deux chantiers pour la
    même entreprise ne partageaient rien, une adresse de facturation n'avait
    nulle part où vivre, et le devis imprimait l'adresse du CHANTIER faute
    d'autre chose.

    Ces deux colonnes historiques restent. Elles ne sont pas migrées vers des
    fiches : deviner qu'« Ets Dupont » et « ETS DUPONT SPRL » sont la même
    entreprise est une décision commerciale, pas une transformation de schéma.
    Un ancien projet reste donc lisible tel quel, et l'écran demande de choisir
    ou de créer une fiche avant la première émission.
    """

    __tablename__ = "clients"
    __table_args__ = (
        UniqueConstraint("id", "organization_id", name="uq_clients_id_organization"),
        CheckConstraint("status IN ('active','archived')", name="ck_client_status"),
        Index("ix_clients_org_status", "organization_id", "status"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    #: Raison sociale, ou simplement le nom pour un particulier.
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    #: Numéro d'entreprise ou de TVA. Facultatif : un particulier n'en a pas.
    company_number: Mapped[str | None] = mapped_column(String(50))
    #: L'adresse de FACTURATION, distincte de celle du chantier — c'est
    #: précisément la distinction qui manquait.
    billing_address: Mapped[str | None] = mapped_column(String(255))
    postal_code: Mapped[str | None] = mapped_column(String(20))
    city: Mapped[str | None] = mapped_column(String(120))
    country_code: Mapped[str] = mapped_column(String(2), nullable=False, default="BE")
    contact_name: Mapped[str | None] = mapped_column(String(200))
    email: Mapped[str | None] = mapped_column(String(255))
    phone: Mapped[str | None] = mapped_column(String(40))
    notes: Mapped[str | None] = mapped_column(Text)
    #: `archived` sort la fiche des listes courantes sans rien détruire, et sans
    #: toucher aux devis déjà émis qui en portent l'instantané.
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


# --------------------------------------------------------------------------
# Documents and human-reviewed extraction
# --------------------------------------------------------------------------


class Document(TimestampMixin, Base):
    """Logical document owned by exactly one project and organisation."""

    __tablename__ = "documents"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name="fk_documents_org_project",
            ondelete="CASCADE",
        ),
        UniqueConstraint("organization_id", "id", name="uq_document_org_id"),
        CheckConstraint("status IN ('active','archived')", name="ck_document_status"),
        CheckConstraint("length(trim(title)) > 0", name="ck_document_title_nonempty"),
        Index("ix_documents_org_project", "organization_id", "project_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    project_id: Mapped[str] = mapped_column(String(36), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class DocumentRevision(TimestampMixin, Base):
    """Immutable original once ``published_at`` is set.

    Database triggers installed by the migration enforce the immutability for
    direct SQL as well as ORM writes. Pipeline progress lives in
    :class:`DocumentStepRun`, never in this row.
    """

    __tablename__ = "document_revisions"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "document_id"],
            ["documents.organization_id", "documents.id"],
            name="fk_document_revisions_org_document",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "organization_id",
            "document_id",
            "revision_number",
            name="uq_document_revision_number",
        ),
        UniqueConstraint("organization_id", "id", name="uq_document_revision_org_id"),
        CheckConstraint("revision_number > 0", name="ck_document_revision_number_positive"),
        CheckConstraint("byte_size > 0", name="ck_document_revision_byte_size_positive"),
        CheckConstraint("length(sha256) = 64", name="ck_document_revision_sha256_length"),
        CheckConstraint(
            "length(trim(media_type)) > 0 AND length(trim(storage_key)) > 0 "
            "AND length(trim(original_filename)) > 0",
            name="ck_document_revision_required_text",
        ),
        CheckConstraint("status IN ('draft','published')", name="ck_document_revision_status"),
        CheckConstraint(
            "(status != 'draft' OR published_at IS NULL) AND "
            "(status != 'published' OR published_at IS NOT NULL)",
            name="ck_document_revision_publication",
        ),
        Index("ix_document_revisions_org_document", "organization_id", "document_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    document_id: Mapped[str] = mapped_column(String(36), nullable=False)
    revision_number: Mapped[int] = mapped_column(Integer, nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False)
    #: Le type lu dans les octets. C'est lui qui fait foi et qui est re-servi.
    media_type: Mapped[str] = mapped_column(String(120), nullable=False)
    #: Le type qu'annonçait le client. Gardé à part, jamais utilisé pour
    #: décider : il ne sert qu'à expliquer un refus ou une incohérence.
    declared_media_type: Mapped[str | None] = mapped_column(String(120))
    storage_key: Mapped[str] = mapped_column(String(512), nullable=False)
    original_filename: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    published_at: Mapped[datetime | None] = mapped_column(DateTime)
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


class DocumentStepRun(TimestampMixin, Base):
    """Idempotent state of one pipeline step for one immutable revision."""

    __tablename__ = "document_step_runs"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "revision_id"],
            ["document_revisions.organization_id", "document_revisions.id"],
            name="fk_document_step_runs_org_revision",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "organization_id",
            "revision_id",
            "step",
            "pipeline_version",
            "prompt_version",
            "model_version",
            name="uq_document_step_run_idempotence",
        ),
        CheckConstraint(
            "step IN ('receive_security','detection','native_text','ocr','tables',"
            "'segmentation','classification','structured_extraction','indexing',"
            "'consistency','human_review')",
            name="ck_document_step_run_step",
        ),
        CheckConstraint(
            "status IN ('pending','running','succeeded','failed')",
            name="ck_document_step_run_status",
        ),
        CheckConstraint("attempt >= 1", name="ck_document_step_run_attempt"),
        CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name="ck_document_step_run_duration",
        ),
        CheckConstraint(
            "status != 'failed' OR (error_code IS NOT NULL AND length(trim(error_code)) > 0)",
            name="ck_document_step_run_failure_code",
        ),
        CheckConstraint(
            "length(trim(pipeline_version)) > 0 AND length(trim(prompt_version)) > 0 "
            "AND length(trim(model_version)) > 0",
            name="ck_document_step_run_versions_nonempty",
        ),
        Index("ix_document_step_runs_org_revision", "organization_id", "revision_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    revision_id: Mapped[str] = mapped_column(String(36), nullable=False)
    step: Mapped[str] = mapped_column(String(40), nullable=False)
    pipeline_version: Mapped[str] = mapped_column(String(80), nullable=False)
    prompt_version: Mapped[str] = mapped_column(String(80), nullable=False, default="none")
    model_version: Mapped[str] = mapped_column(String(80), nullable=False, default="none")
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    attempt: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    started_at: Mapped[datetime | None] = mapped_column(DateTime)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime)
    duration_ms: Mapped[int | None] = mapped_column(Integer)
    error_code: Mapped[str | None] = mapped_column(String(80))
    error_summary: Mapped[str | None] = mapped_column(String(255))


class SourceCitation(TimestampMixin, Base):
    """Resolvable source location; never a free-form “see page” string."""

    __tablename__ = "source_citations"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "revision_id"],
            ["document_revisions.organization_id", "document_revisions.id"],
            name="fk_source_citations_org_revision",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "organization_id",
            "revision_id",
            "id",
            name="uq_source_citation_org_revision_id",
        ),
        CheckConstraint("page >= 1", name="ck_source_citation_page"),
        CheckConstraint("char_start >= 0", name="ck_source_citation_char_start"),
        CheckConstraint("char_end > char_start", name="ck_source_citation_char_range"),
        CheckConstraint(
            "x0 >= 0 AND x0 <= 1 AND y0 >= 0 AND y0 <= 1 AND "
            "x1 >= 0 AND x1 <= 1 AND y1 >= 0 AND y1 <= 1 AND "
            "x0 < x1 AND y0 < y1",
            name="ck_source_citation_bbox",
        ),
        CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name="ck_source_citation_confidence",
        ),
        CheckConstraint(
            "length(trim(extractor)) > 0",
            name="ck_source_citation_extractor_nonempty",
        ),
        Index("ix_source_citations_org_revision", "organization_id", "revision_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    revision_id: Mapped[str] = mapped_column(String(36), nullable=False)
    page: Mapped[int] = mapped_column(Integer, nullable=False)
    char_start: Mapped[int] = mapped_column(Integer, nullable=False)
    char_end: Mapped[int] = mapped_column(Integer, nullable=False)
    x0: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    y0: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    x1: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    y1: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    sheet: Mapped[str | None] = mapped_column(String(120))
    layer: Mapped[str | None] = mapped_column(String(120))
    object_id: Mapped[str | None] = mapped_column(String(120))
    extractor: Mapped[str] = mapped_column(String(120), nullable=False)
    confidence: Mapped[Decimal] = mapped_column(Amount, nullable=False)


class ExtractionProposal(TimestampMixin, Base):
    """Machine output awaiting a separate append-only human decision."""

    __tablename__ = "extraction_proposals"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "revision_id", "citation_id"],
            [
                "source_citations.organization_id",
                "source_citations.revision_id",
                "source_citations.id",
            ],
            name="fk_extraction_proposals_org_revision_citation",
            ondelete="CASCADE",
        ),
        UniqueConstraint("organization_id", "id", name="uq_extraction_proposal_org_id"),
        CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name="ck_extraction_proposal_confidence",
        ),
        CheckConstraint(
            "status IN ('proposed','accepted','corrected','rejected')",
            name="ck_extraction_proposal_status",
        ),
        CheckConstraint(
            "length(trim(schema_name)) > 0 AND length(trim(schema_version)) > 0 "
            "AND length(trim(pipeline_version)) > 0 "
            "AND length(trim(prompt_version)) > 0 "
            "AND length(trim(model_version)) > 0",
            name="ck_extraction_proposal_versions_nonempty",
        ),
        Index("ix_extraction_proposals_org_revision", "organization_id", "revision_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    revision_id: Mapped[str] = mapped_column(String(36), nullable=False)
    citation_id: Mapped[str] = mapped_column(String(36), nullable=False)
    schema_name: Mapped[str] = mapped_column(String(120), nullable=False)
    schema_version: Mapped[str] = mapped_column(String(80), nullable=False)
    value: Mapped[dict] = mapped_column(SAJSON, nullable=False)
    confidence: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    pipeline_version: Mapped[str] = mapped_column(String(80), nullable=False)
    prompt_version: Mapped[str] = mapped_column(String(80), nullable=False)
    model_version: Mapped[str] = mapped_column(String(80), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="proposed")


class ValidationDecision(Base):
    """Append-only record of one human acceptance, correction or rejection."""

    __tablename__ = "validation_decisions"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "proposal_id"],
            ["extraction_proposals.organization_id", "extraction_proposals.id"],
            name="fk_validation_decisions_org_proposal",
            ondelete="RESTRICT",
        ),
        ForeignKeyConstraint(
            ["actor_user_id", "organization_id"],
            ["memberships.user_id", "memberships.organization_id"],
            name="fk_validation_decisions_actor_membership",
            ondelete="RESTRICT",
        ),
        CheckConstraint(
            "decision IN ('accepted','corrected','rejected')",
            name="ck_validation_decision_value",
        ),
        CheckConstraint(
            "length(trim(reason)) > 0",
            name="ck_validation_decision_reason",
        ),
        CheckConstraint(
            "(decision != 'corrected' OR (before_value IS NOT NULL AND after_value IS NOT NULL)) "
            "AND (decision NOT IN ('accepted','rejected') OR "
            "(before_value IS NULL AND after_value IS NULL))",
            name="ck_validation_decision_correction_payload",
        ),
        Index("ix_validation_decisions_org_proposal", "organization_id", "proposal_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    proposal_id: Mapped[str] = mapped_column(String(36), nullable=False)
    actor_user_id: Mapped[str] = mapped_column(String(36), nullable=False)
    decision: Mapped[str] = mapped_column(String(20), nullable=False)
    reason: Mapped[str] = mapped_column(Text, nullable=False)
    before_value: Mapped[dict | None] = mapped_column(SAJSON(none_as_null=True))
    after_value: Mapped[dict | None] = mapped_column(SAJSON(none_as_null=True))
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)


# --------------------------------------------------------------------------
# Price library
# --------------------------------------------------------------------------


class PriceBook(TimestampMixin, Base):
    __tablename__ = "price_books"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_price_books_id_organization"),
        UniqueConstraint("organization_id", "name", name="uq_pricebook_org_name"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(160), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    is_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class PriceBookVersion(TimestampMixin, Base):
    """A published version is immutable; drafts are where imports land."""

    __tablename__ = "price_book_versions"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_price_book_versions_id_organization"),
        ForeignKeyConstraint(
            ["price_book_id", "organization_id"],
            ["price_books.id", "price_books.organization_id"],
            name="fk_price_book_versions_price_book_tenant",
            ondelete="CASCADE",
        ),
        UniqueConstraint("price_book_id", "version_number", name="uq_pbv_book_number"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("price_books.id", ondelete="CASCADE"), nullable=False, index=True
    )
    version_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    label: Mapped[str | None] = mapped_column(String(160))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    published_at: Mapped[datetime | None] = mapped_column(DateTime)
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


class PriceItem(TimestampMixin, Base):
    __tablename__ = "price_items"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_price_items_id_organization"),
        ForeignKeyConstraint(
            ["price_book_version_id", "organization_id"],
            ["price_book_versions.id", "price_book_versions.organization_id"],
            name="fk_price_items_price_book_version_tenant",
            ondelete="CASCADE",
        ),
        CheckConstraint(
            "resource_kind IN ('material','labor','equipment','transport',"
            "'disposal','subcontract','other')",
            name="ck_price_item_resource_kind",
        ),
        CheckConstraint(
            "status IN ('active','draft','archived','superseded')",
            name="ck_price_item_status",
        ),
        CheckConstraint(
            "confidence IN ('declared','quoted','contracted','estimated')",
            name="ck_price_item_confidence",
        ),
        CheckConstraint(
            "valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from",
            name="ck_price_item_validity_range",
        ),
        CheckConstraint(
            "lead_time_days IS NULL OR (lead_time_days >= 0 AND lead_time_days <= 3650)",
            name="ck_price_item_lead_time",
        ),
        UniqueConstraint("price_book_version_id", "code", name="uq_priceitem_version_code"),
        Index("ix_price_items_org_family", "organization_id", "family"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("price_book_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    code: Mapped[str] = mapped_column(String(60), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    family: Mapped[str | None] = mapped_column(String(60))
    resource_kind: Mapped[str] = mapped_column(String(30), nullable=False, default="material")
    unit_code: Mapped[str] = mapped_column(String(12), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    supplier_name: Mapped[str | None] = mapped_column(String(200))
    region_code: Mapped[str | None] = mapped_column(String(10))
    valid_from: Mapped[datetime | None] = mapped_column(Date)
    valid_to: Mapped[datetime | None] = mapped_column(Date)
    min_quantity: Mapped[Decimal | None] = mapped_column(Amount)
    lead_time_days: Mapped[int | None] = mapped_column(Integer)
    source: Mapped[str | None] = mapped_column(String(255))
    conditions: Mapped[str | None] = mapped_column(Text)
    indexation: Mapped[str | None] = mapped_column(String(120))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    confidence: Mapped[str] = mapped_column(String(20), nullable=False, default="declared")
    is_demo_data: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    notes: Mapped[str | None] = mapped_column(Text)


class CompositePriceRow(TimestampMixin, Base):
    """A reusable sub-detail (sous-détail de prix)."""

    __tablename__ = "composite_prices"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        ForeignKeyConstraint(
            ["price_book_version_id", "organization_id"],
            ["price_book_versions.id", "price_book_versions.organization_id"],
            name="fk_composite_prices_price_book_version_tenant",
            ondelete="CASCADE",
        ),
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_composite_prices_id_organization"),
        UniqueConstraint("price_book_version_id", "code", name="uq_composite_version_code"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("price_book_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    code: Mapped[str] = mapped_column(String(60), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    unit_code: Mapped[str] = mapped_column(String(12), nullable=False)
    notes: Mapped[str | None] = mapped_column(Text)
    is_demo_data: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    #: Le jeton de concurrence, incrémenté à chaque modification.
    #:
    #: `updated_at` aurait pu servir, à deux réserves près : il ne bouge pas
    #: quand seuls les COMPOSANTS changent — or c'est le cas courant — et deux
    #: écritures tombant dans la même graduation d'horloge porteraient le même
    #: jeton. Un entier ne laisse aucun de ces deux doutes, et c'est ce qui
    #: permet de refuser une modification fondée sur une version obsolète
    #: plutôt que de l'écraser en silence.
    revision: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    components: Mapped[list[CompositeComponentRow]] = relationship(
        back_populates="composite",
        cascade="all, delete-orphan",
        order_by="CompositeComponentRow.sort_index",
        # Deux chemins de clé relient désormais ces deux tables : la clé simple
        # `composite_price_id`, et la clé composite qui lui adjoint
        # `organization_id`. SQLAlchemy refuse de choisir — il lève
        # `AmbiguousForeignKeysError` — et il a raison de refuser : c'est à
        # nous de dire lequel porte la relation.
        foreign_keys="CompositeComponentRow.composite_price_id",
    )


class CompositeComponentRow(TimestampMixin, Base):
    """One row of a sub-detail.

    A single wide table with nullable columns keyed by ``component_type`` keeps
    the sub-detail readable in one query. Which columns are required for which
    type is validated in :mod:`metreo_api.services.composites`, and the
    check constraint below stops an unknown type from being stored at all.
    """

    __tablename__ = "composite_components"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        ForeignKeyConstraint(
            ["composite_price_id", "organization_id"],
            ["composite_prices.id", "composite_prices.organization_id"],
            name="fk_composite_components_composite_price_tenant",
            ondelete="CASCADE",
        ),
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        ForeignKeyConstraint(
            ["price_item_id", "organization_id"],
            ["price_items.id", "price_items.organization_id"],
            name="fk_composite_components_price_item_tenant",
            ondelete="SET NULL (price_item_id)",
        ),
        CheckConstraint(
            "component_type IN ('consumption','output_rate','rotation','lump_sum')",
            name="ck_composite_component_type",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    composite_price_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("composite_prices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    sort_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    component_type: Mapped[str] = mapped_column(String(20), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    resource_kind: Mapped[str] = mapped_column(String(30), nullable=False, default="other")
    price_item_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("price_items.id", ondelete="SET NULL")
    )

    # consumption
    consumption: Mapped[Decimal | None] = mapped_column(Amount)
    resource_unit_code: Mapped[str | None] = mapped_column(String(12))
    unit_price: Mapped[Decimal | None] = mapped_column(Amount)
    loss_ratio: Mapped[Decimal | None] = mapped_column(Amount)
    convert_boq_quantity: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    density_value: Mapped[Decimal | None] = mapped_column(Amount)
    density_source: Mapped[str | None] = mapped_column(String(255))

    # output rate
    output_rate: Mapped[Decimal | None] = mapped_column(Amount)
    hourly_rate: Mapped[Decimal | None] = mapped_column(Amount)
    crew_size: Mapped[Decimal | None] = mapped_column(Amount)

    # rotation
    payload_value: Mapped[Decimal | None] = mapped_column(Amount)
    payload_unit_code: Mapped[str | None] = mapped_column(String(12))
    cost_per_rotation: Mapped[Decimal | None] = mapped_column(Amount)
    round_up: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    distance_km: Mapped[Decimal | None] = mapped_column(Amount)
    rate_per_km: Mapped[Decimal | None] = mapped_column(Amount)

    # lump sum
    lump_sum_amount: Mapped[Decimal | None] = mapped_column(Amount)

    composite: Mapped[CompositePriceRow] = relationship(
        back_populates="components",
        foreign_keys="CompositeComponentRow.composite_price_id",
    )


# --------------------------------------------------------------------------
# CSV import staging
# --------------------------------------------------------------------------


class ImportBatch(TimestampMixin, Base):
    """A previewed import. Nothing reaches ``price_items`` before ``commit``."""

    __tablename__ = "import_batches"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        ForeignKeyConstraint(
            ["price_book_version_id", "organization_id"],
            ["price_book_versions.id", "price_book_versions.organization_id"],
            name="fk_import_batches_price_book_version_tenant",
            ondelete="CASCADE",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("price_book_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="previewed")
    strategy: Mapped[str] = mapped_column(String(20), nullable=False, default="create")
    row_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    valid_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    error_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    duplicate_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    column_mapping: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    committed_at: Mapped[datetime | None] = mapped_column(DateTime)

    rows: Mapped[list[ImportBatchRow]] = relationship(
        back_populates="batch", cascade="all, delete-orphan", order_by="ImportBatchRow.line_number"
    )


class ImportBatchRow(Base):
    __tablename__ = "import_batch_rows"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    batch_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("import_batches.id", ondelete="CASCADE"), nullable=False, index=True
    )
    line_number: Mapped[int] = mapped_column(Integer, nullable=False)
    raw: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    normalized: Mapped[dict | None] = mapped_column(SAJSON)
    is_valid: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    is_duplicate: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    errors: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)

    batch: Mapped[ImportBatch] = relationship(back_populates="rows")


# --------------------------------------------------------------------------
# Bill of quantities
# --------------------------------------------------------------------------


class BillOfQuantities(TimestampMixin, Base):
    __tablename__ = "bills_of_quantities"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_bills_of_quantities_id_organization"),
        ForeignKeyConstraint(
            ["project_id", "organization_id"],
            ["projects.id", "projects.organization_id"],
            name="fk_bills_of_quantities_project_tenant",
            ondelete="CASCADE",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    source: Mapped[str] = mapped_column(String(20), nullable=False, default="manual")
    revision: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    notes: Mapped[str | None] = mapped_column(Text)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class BoqItem(TimestampMixin, Base):
    __tablename__ = "boq_items"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        UniqueConstraint("id", "organization_id", name="uq_boq_items_id_organization"),
        ForeignKeyConstraint(
            ["parent_id", "organization_id"],
            ["boq_items.id", "boq_items.organization_id"],
            name="fk_boq_items_parent_tenant",
            ondelete="CASCADE",
        ),
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        ForeignKeyConstraint(
            ["boq_id", "organization_id"],
            ["bills_of_quantities.id", "bills_of_quantities.organization_id"],
            name="fk_boq_items_boq_tenant",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["price_item_id", "organization_id"],
            ["price_items.id", "price_items.organization_id"],
            name="fk_boq_items_price_item_tenant",
            ondelete="SET NULL (price_item_id)",
        ),
        ForeignKeyConstraint(
            ["composite_price_id", "organization_id"],
            ["composite_prices.id", "composite_prices.organization_id"],
            name="fk_boq_items_composite_price_tenant",
            ondelete="SET NULL (composite_price_id)",
        ),
        CheckConstraint(
            "price_item_id IS NULL OR composite_price_id IS NULL",
            name="ck_boq_item_single_price_source",
        ),
        UniqueConstraint("boq_id", "position", name="uq_boqitem_boq_position"),
        CheckConstraint(
            "kind IN ('section','item','option','variant','provisional')",
            name="ck_boq_item_kind",
        ),
        CheckConstraint(
            "status IN ('proposed','verified','approved','rejected')",
            name="ck_boq_item_status",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    boq_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("bills_of_quantities.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    parent_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("boq_items.id", ondelete="CASCADE")
    )
    sort_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    position: Mapped[str] = mapped_column(String(40), nullable=False)
    code: Mapped[str | None] = mapped_column(String(60))
    designation: Mapped[str] = mapped_column(Text, nullable=False)
    unit_code: Mapped[str] = mapped_column(String(12), nullable=False, default="fft")
    quantity: Mapped[Decimal] = mapped_column(Amount, nullable=False, default=Decimal("0"))
    kind: Mapped[str] = mapped_column(String(20), nullable=False, default="item")
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="proposed")
    formula: Mapped[str | None] = mapped_column(Text)
    client_quantity: Mapped[Decimal | None] = mapped_column(Amount)
    notes: Mapped[str | None] = mapped_column(Text)
    price_item_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("price_items.id", ondelete="SET NULL")
    )
    composite_price_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("composite_prices.id", ondelete="SET NULL")
    )


# --------------------------------------------------------------------------
# Estimates
# --------------------------------------------------------------------------


class Estimate(TimestampMixin, Base):
    __tablename__ = "estimates"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        UniqueConstraint("id", "organization_id", name="uq_estimates_id_organization"),
        ForeignKeyConstraint(
            ["project_id", "organization_id"],
            ["projects.id", "projects.organization_id"],
            name="fk_estimates_project_tenant",
            ondelete="CASCADE",
        ),
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        ForeignKeyConstraint(
            ["boq_id", "organization_id"],
            ["bills_of_quantities.id", "bills_of_quantities.organization_id"],
            name="fk_estimates_boq_tenant",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["price_book_version_id", "organization_id"],
            ["price_book_versions.id", "price_book_versions.organization_id"],
            name="fk_estimates_price_book_version_tenant",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    boq_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("bills_of_quantities.id", ondelete="CASCADE"), nullable=False
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("price_book_versions.id"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class EstimateVersion(TimestampMixin, Base):
    """A frozen version stores the computed result *and* its inputs.

    ``snapshot`` holds the resolved lines, the price book version identifier,
    the markup policy and the tax rates that were in force. Recomputing it later
    reproduces the same numbers even if the library has moved on, which is what
    acceptance scenarios 6 and 7 require.
    """

    __tablename__ = "estimate_versions"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        ForeignKeyConstraint(
            ["estimate_id", "organization_id"],
            ["estimates.id", "estimates.organization_id"],
            name="fk_estimate_versions_estimate_tenant",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["price_book_version_id", "organization_id"],
            ["price_book_versions.id", "price_book_versions.organization_id"],
            name="fk_estimate_versions_price_book_version_tenant",
        ),
        UniqueConstraint("estimate_id", "version_number", name="uq_estimateversion_number"),
        # La clé que doublent les frontières multi-tenant pointant ICI. Un devis
        # émis désigne une version ET son organisation ; sans cette unicité,
        # SQLite refuse la clé composite avec « foreign key mismatch », et
        # PostgreSQL exigerait la même chose.
        UniqueConstraint("id", "organization_id", name="uq_estimate_versions_id_organization"),
        CheckConstraint(
            "status IN ('draft','frozen','superseded')", name="ck_estimate_version_status"
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    estimate_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("estimates.id", ondelete="CASCADE"), nullable=False, index=True
    )
    version_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    label: Mapped[str | None] = mapped_column(String(200))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    price_book_version_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("price_book_versions.id"), nullable=False
    )
    markup: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    taxes: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    rounding: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    missing_price_policy: Mapped[str] = mapped_column(String(10), nullable=False, default="block")
    snapshot: Mapped[dict | None] = mapped_column(SAJSON)
    snapshot_sha256: Mapped[str | None] = mapped_column(String(64))
    #: Totaux **bruts**, non arrondis, tels que le moteur les a produits. Ce
    #: sont eux qui servent aux calculs internes et aux comparaisons ; ils ne
    #: sont pas ce que le devis imprime.
    total_selling_price_ht: Mapped[Decimal | None] = mapped_column(Amount)
    total_ttc: Mapped[Decimal | None] = mapped_column(Amount)
    #: Totaux **du document**, figés au gel : exactement les nombres que le
    #: devis remis au client porte, sous la convention « le document
    #: s'additionne » (voir `docs/ARRONDI_DES_DOCUMENTS.md`).
    #:
    #: Deux colonnes distinctes plutôt qu'une réinterprétation des précédentes :
    #: brut et imprimé ne coïncident pas, et une colonne qui aurait porté les
    #: deux sens selon la date de la ligne aurait été un piège permanent.
    #:
    #: `NULL` a un sens précis et unique : *le total documentaire de cette
    #: version gelée n'a pas pu être reconstruit*. Il n'est jamais remplacé en
    #: silence par l'arrondi du brut — un lecteur doit savoir qu'il ne dispose
    #: pas du nombre imprimé. Une version brouillon n'en porte pas non plus :
    #: son document se recalcule à la demande.
    document_total_ht: Mapped[Decimal | None] = mapped_column(Amount)
    document_total_ttc: Mapped[Decimal | None] = mapped_column(Amount)
    frozen_at: Mapped[datetime | None] = mapped_column(DateTime)
    frozen_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


class IssuedQuote(TimestampMixin, Base):
    """Un devis REMIS au client : numéroté, daté, figé, et téléchargeable.

    Une version gelée est un calcul reproductible ; ce n'en est pas encore un
    document commercial. Il lui manque un numéro, une date d'émission, une
    validité, un destinataire, et un fichier que l'entreprise peut transmettre.

    Tout ce que le document imprime est recopié ici au moment de l'émission —
    l'organisation, le client, le chantier, les lignes et les totaux. C'est la
    raison d'être de cette table : modifier ensuite la fiche client, les taux
    ou l'organisation ne change pas un devis déjà remis. Le PDF n'est jamais
    reconstruit à partir des tables vivantes ; il est lu sur le volume, tel
    qu'il a été écrit, et son empreinte le prouve.

    Une version ne s'émet qu'une fois : `uq_issued_quote_version`. Corriger un
    devis remis n'est pas une modification, c'est une nouvelle version suivie
    d'une nouvelle émission — et l'ancienne reste.

    **Aucun parent ordinaire ne l'emporte.** Chantier, estimation et version
    gelée retiennent en `RESTRICT`, et non plus en `CASCADE`. Reproduit sur une
    base jetable : supprimer le chantier faisait disparaître le devis remis
    SANS un mot, et laissait son PDF sur le volume — un fichier que plus
    aucune ligne ne désignait, et un document transmis à un client dont
    l'entreprise n'avait plus trace. Trois des cinq suppressions éprouvées se
    comportaient ainsi.

    **L'organisation non plus.** Elle emportait encore ses devis — mesuré : la
    ligne partait, le journal d'audit qui en gardait trace partait avec, et le
    PDF restait sur le volume. Une destruction motivée par un effacement
    détruisait donc sa propre preuve tout en conservant le document. Depuis
    `a5b6c7d8e9fa`, `organization_id` retient en `RESTRICT` lui aussi.

    Détruire une organisation reste possible, mais par une seule porte
    nommée : `services/conservation.py` inscrit au registre ce qu'elle va
    détruire AVANT de le détruire, et cette inscription — qui survit à
    l'organisation — est ce que le déclencheur de base exige pour laisser
    passer la suppression d'un devis. Voir l'ADR 0006.
    """

    __tablename__ = "issued_quotes"
    __table_args__ = (
        ForeignKeyConstraint(
            ["project_id", "organization_id"],
            ["projects.id", "projects.organization_id"],
            name="fk_issued_quotes_project_tenant",
            ondelete="RESTRICT",
        ),
        ForeignKeyConstraint(
            ["estimate_version_id", "organization_id"],
            ["estimate_versions.id", "estimate_versions.organization_id"],
            name="fk_issued_quotes_version_tenant",
            ondelete="RESTRICT",
        ),
        ForeignKeyConstraint(
            ["client_id", "organization_id"],
            ["clients.id", "clients.organization_id"],
            name="fk_issued_quotes_client_tenant",
        ),
        UniqueConstraint("id", "organization_id", name="uq_issued_quotes_id_organization"),
        #: Le numéro est unique DANS l'organisation, et c'est la base qui le
        #: tient — le verrou de séquence n'est qu'une convention entre écrivains
        #: bien élevés.
        UniqueConstraint("organization_id", "number", name="uq_issued_quote_number"),
        UniqueConstraint("estimate_version_id", name="uq_issued_quote_version"),
        Index("ix_issued_quotes_org_project", "organization_id", "project_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    #: RESTRICT, et pas CASCADE : c'était la dernière porte par laquelle un
    #: devis émis disparaissait sans un mot.
    #:
    #: Mesuré avant correction, sur base jetable : un `DELETE FROM
    #: organizations` effaçait la ligne du devis, effaçait le journal d'audit
    #: qui en gardait la trace, et laissait le PDF du client sur le volume,
    #: octet pour octet. Une purge motivée par un effacement détruisait donc sa
    #: propre preuve tout en conservant le document — exactement à l'envers.
    #:
    #: La destruction d'une organisation reste possible, mais elle passe
    #: désormais par une seule porte nommée : `services/conservation.py`, qui
    #: inscrit ce qu'elle va détruire AVANT de le détruire, dans un registre
    #: qui, lui, survit à l'organisation.
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    estimate_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("estimates.id", ondelete="RESTRICT"), nullable=False
    )
    estimate_version_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("estimate_versions.id", ondelete="RESTRICT"), nullable=False
    )
    #: Sans action : `NO ACTION` refuse déjà, et c'est ce qu'on veut. La fiche
    #: client s'archive, elle ne se supprime pas — voir `routers/clients.py`.
    client_id: Mapped[str] = mapped_column(String(36), ForeignKey("clients.id"), nullable=False)

    #: Le numéro imprimé, rendu par le motif de l'organisation.
    number: Mapped[str] = mapped_column(String(60), nullable=False)
    #: L'année et le rang qui l'ont produit, conservés séparément : ils
    #: expliquent le numéro, et permettent d'allouer le suivant sans le
    #: réinterpréter à l'envers.
    sequence_year: Mapped[int] = mapped_column(Integer, nullable=False)
    sequence_number: Mapped[int] = mapped_column(Integer, nullable=False)

    issued_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    valid_until: Mapped[date] = mapped_column(Date, nullable=False)
    #: Conditions et note au client, telles qu'imprimées. Configurables, jamais
    #: gravées : ce dépôt n'affirme aucune mention légale qu'il ne peut pas
    #: démontrer.
    terms: Mapped[str | None] = mapped_column(Text)

    #: Ce que le document dit, figé. Quatre instantanés distincts plutôt qu'un
    #: seul objet : on les relit séparément, et un lecteur voit tout de suite ce
    #: qui vient d'où.
    organization_snapshot: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    client_snapshot: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    project_snapshot: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    document_snapshot: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    #: La décision prise AU MOMENT de l'émission, et non relue plus tard dans
    #: les réglages : faire apparaître les coûts internes est un choix qui
    #: engage, et il se lit sur le devis lui-même.
    include_internal_costs: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    #: Le fichier remis, sur le même volume que les pièces de chantier.
    pdf_storage_key: Mapped[str] = mapped_column(String(500), nullable=False)
    pdf_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    pdf_byte_size: Mapped[int] = mapped_column(Integer, nullable=False)

    issued_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


# --------------------------------------------------------------------------
# Le cycle commercial d'un devis remis
# --------------------------------------------------------------------------

#: Les canaux par lesquels un devis circule ou une réponse revient.
CANAUX_DE_DEVIS = ("public_link", "email", "phone", "meeting", "other")

#: Ce qui peut arriver à un devis remis. Rien d'autre ne s'écrit.
EVENEMENTS_DE_DEVIS = (
    "link_created",
    "link_revoked",
    "transmitted",
    "viewed",
    "accepted",
    "declined",
    "correction",
)

#: Les deux seules réponses finales. Un devis n'en porte qu'une.
DECISIONS = ("accepted", "declined")


class QuoteEvent(TimestampMixin, Base):
    """Ce qui est arrivé à un devis remis, dans l'ordre, et sans retour.

    Le devis et son PDF ne bougent pas ; son ÉTAT commercial, lui, évolue. Cet
    état n'est stocké nulle part : il se déduit de ces événements et de la date
    du jour — c'est ce qui rend « Expiré » exact à la seconde sans tâche
    planifiée, et ce qui interdit à un état enregistré de diverger de son
    histoire.

    **Rien ne se réécrit.** Une erreur de saisie interne se corrige par un
    événement de type `correction` qui DÉSIGNE l'original et porte un motif
    obligatoire ; l'original reste lisible, barré plutôt qu'effacé. Un
    déclencheur refuse `UPDATE` et `DELETE` sur cette table : la promesse
    « append-only » n'est pas une convention entre gens bien élevés.

    Deux dates, jamais une seule. `effective_at` est le moment où la chose a eu
    lieu — un accord donné au téléphone jeudi — et `recorded_at` celui où
    quelqu'un l'a écrite ici, le lundi suivant. Les confondre ferait mentir la
    chronologie sur l'un ou l'autre.
    """

    __tablename__ = "quote_events"
    __table_args__ = (
        ForeignKeyConstraint(
            ["issued_quote_id", "organization_id"],
            ["issued_quotes.id", "issued_quotes.organization_id"],
            name="fk_quote_events_quote_tenant",
            ondelete="CASCADE",
        ),
        CheckConstraint(
            "kind IN ('" + "','".join(EVENEMENTS_DE_DEVIS) + "')", name="ck_quote_event_kind"
        ),
        CheckConstraint(
            "channel IS NULL OR channel IN ('" + "','".join(CANAUX_DE_DEVIS) + "')",
            name="ck_quote_event_channel",
        ),
        #: Une correction sans motif ne corrige rien : elle efface sans dire
        #: pourquoi. Et un motif sans correction n'a personne à désigner.
        CheckConstraint(
            "(corrects_event_id IS NULL AND correction_reason IS NULL) "
            "OR (corrects_event_id IS NOT NULL AND correction_reason IS NOT NULL "
            "AND kind = 'correction')",
            name="ck_quote_event_correction",
        ),
        Index("ix_quote_events_quote", "issued_quote_id", "recorded_at"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    issued_quote_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("issued_quotes.id", ondelete="CASCADE"), nullable=False
    )
    #: L'empreinte du PDF au moment de l'événement. Recopiée plutôt que jointe :
    #: elle prouve, dans la ligne même, DE QUEL document il est question.
    pdf_sha256: Mapped[str] = mapped_column(String(64), nullable=False)

    kind: Mapped[str] = mapped_column(String(20), nullable=False)
    channel: Mapped[str | None] = mapped_column(String(20))

    #: Qui, dans l'entreprise, a provoqué l'événement. Absent quand il vient du
    #: destinataire par le lien public — et c'est le point.
    actor_user_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    actor_email: Mapped[str | None] = mapped_column(String(255))

    #: Ce que le répondant DÉCLARE de lui-même. Aucune vérification d'identité
    #: n'est faite, et l'interface le dit : ce n'est pas une signature
    #: électronique qualifiée.
    respondent_name: Mapped[str | None] = mapped_column(String(200))
    respondent_email: Mapped[str | None] = mapped_column(String(255))

    comment: Mapped[str | None] = mapped_column(Text)

    effective_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    recorded_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)

    corrects_event_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("quote_events.id"))
    correction_reason: Mapped[str | None] = mapped_column(Text)

    request_id: Mapped[str | None] = mapped_column(String(64))


class QuoteShareLink(TimestampMixin, Base):
    """Le lien par lequel un destinataire consulte un devis, sans compte.

    **Le secret n'est pas ici.** Seule son empreinte SHA-256 est stockée : une
    copie de la base ne permet pas d'ouvrir un devis. Le secret brut n'est rendu
    qu'une fois, à la création, et n'est jamais journalisé.

    Le lien porte sa propre expiration, qui ne dépasse jamais la validité du
    devis : un document périmé ne se consulte pas plus longtemps que ce que
    l'entreprise a promis. La révocation est immédiate et vaut aussi pour les
    sessions publiques déjà ouvertes — celles-ci désignent le lien, et un lien
    révoqué les invalide toutes.
    """

    __tablename__ = "quote_share_links"
    __table_args__ = (
        ForeignKeyConstraint(
            ["issued_quote_id", "organization_id"],
            ["issued_quotes.id", "issued_quotes.organization_id"],
            name="fk_quote_share_links_quote_tenant",
            ondelete="CASCADE",
        ),
        UniqueConstraint("id", "organization_id", name="uq_quote_share_links_id_organization"),
        #: L'empreinte est l'identifiant de recherche : deux liens ne peuvent
        #: pas partager la même, et la contrainte le tient.
        UniqueConstraint("secret_sha256", name="uq_quote_share_link_secret"),
        Index("ix_quote_share_links_quote", "issued_quote_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    issued_quote_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("issued_quotes.id", ondelete="CASCADE"), nullable=False
    )
    secret_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime)
    revoked_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


class QuotePublicSession(Base):
    """La session courte d'un destinataire, après échange du secret.

    Elle vit dans un cookie `HttpOnly` : le secret du lien, lui, ne survit pas
    à la première seconde de la page — il est lu dans le fragment, retiré de
    l'historique, échangé, et oublié.

    Comme le lien, seule l'empreinte du jeton est stockée. La session ne porte
    aucun droit propre : elle désigne un lien, et tout ce que le lien perd —
    révocation, expiration — elle le perd au même instant.
    """

    __tablename__ = "quote_public_sessions"
    __table_args__ = (
        ForeignKeyConstraint(
            ["share_link_id", "organization_id"],
            ["quote_share_links.id", "quote_share_links.organization_id"],
            name="fk_quote_public_sessions_link_tenant",
            ondelete="CASCADE",
        ),
        UniqueConstraint("token_sha256", name="uq_quote_public_session_token"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    share_link_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("quote_share_links.id", ondelete="CASCADE"), nullable=False
    )
    token_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


# --------------------------------------------------------------------------
# Audit
# --------------------------------------------------------------------------


class AuditEvent(Base):
    """Append-only journal with a per-organisation hash chain.

    ``previous_hash`` links each row to the one before it inside the same
    organisation. Deleting or editing a row breaks the chain, which
    ``/audit/verify`` detects. This is tamper-evidence, not tamper-proofing —
    stated as such in the security threat model.
    """

    __tablename__ = "audit_events"
    __table_args__ = (
        Index("ix_audit_org_occurred", "organization_id", "occurred_at"),
        UniqueConstraint("organization_id", "sequence", name="uq_audit_org_sequence"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    sequence: Mapped[int] = mapped_column(Integer, nullable=False)
    occurred_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)
    actor_user_id: Mapped[str | None] = mapped_column(String(36))
    actor_email: Mapped[str | None] = mapped_column(String(255))
    action: Mapped[str] = mapped_column(String(80), nullable=False)
    object_type: Mapped[str] = mapped_column(String(60), nullable=False)
    object_id: Mapped[str | None] = mapped_column(String(36))
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    request_id: Mapped[str | None] = mapped_column(String(64))
    #: Version du schéma de hash sous laquelle l'événement a été scellé. Une
    #: constante Python seule ne permettrait pas de revérifier durablement des
    #: événements créés sous plusieurs versions : la vérification lirait le code
    #: d'aujourd'hui pour juger un scellé d'hier.
    #: Renseigné explicitement par `audit.record()`. Pas de valeur par défaut :
    #: un défaut silencieux à 1 marquerait un événement scellé en v2 comme v1,
    #: et le rendrait invérifiable.
    hash_schema_version: Mapped[int] = mapped_column(Integer, nullable=False)
    previous_hash: Mapped[str | None] = mapped_column(String(64))
    hash: Mapped[str] = mapped_column(String(64), nullable=False)


#: Les états d'une purge d'organisation.
#:
#: `requested` n'autorise RIEN. C'est la correction de fond apportée après la
#: première version : une demande inscrite y ouvrait la porte, et une demande
#: abandonnée la laissait ouverte indéfiniment. Seul `executing` autorise, et
#: seulement tant que sa fenêtre court.
ETATS_DE_PURGE = ("requested", "executing", "rows_deleted", "completed", "failed")

#: Combien de temps une autorisation d'exécution reste valable.
#:
#: Assez pour détruire les lignes d'une organisation et retirer ses fichiers ;
#: trop court pour qu'une fenêtre oubliée devienne un droit permanent. La base
#: compare cette borne à sa propre horloge, elle ne fait pas confiance à
#: l'appelant.
MINUTES_D_AUTORISATION = 15

#: Pourquoi une organisation est détruite. Une liste FERMÉE, et c'est le point.
#:
#: Le champ était auparavant un texte libre de 500 caractères. Un registre
#: censé prouver une destruction sans conserver ce qu'elle a effacé ne peut pas
#: offrir une zone où l'on écrit « à la demande de M. Dupont, Terrassements
#: Untel » — la donnée personnelle rentre alors par la porte prévue pour la
#: faire sortir. Le code dit la CATÉGORIE ; la référence opaque, elle, permet
#: de retrouver le dossier ailleurs, dans un système dont ce n'est pas le rôle
#: de garantir l'effacement.
MOTIFS_DE_PURGE = (
    #: Le contrat qui liait l'entreprise à Metreo a pris fin.
    "contract_ended",
    #: Une personne concernée a demandé l'effacement.
    "subject_request",
    #: La durée de conservation décidée est échue et l'entreprise ne veut pas
    #: conserver au-delà.
    "retention_elapsed",
    #: L'organisation était un doublon d'une autre.
    "duplicate_organization",
    #: Réinitialisation du jeu de démonstration.
    "demo_reset",
    #: Organisation créée pour une recette ou un banc d'essai.
    "test_fixture",
)


class QuoteRetentionDecision(Base):
    """Une décision de conservation : la durée, ET ce qui la fonde.

    Un nombre d'années seul n'est pas une décision — c'est une opinion sans
    auteur. La première version stockait exactement cela, un `Integer` nullable
    sur les réglages de l'organisation, et rien n'obligeait quiconque à dire
    d'où il sortait. Une durée de conservation engage l'entreprise : elle vient
    d'un droit applicable, elle a une source, elle prend effet à une date, et
    quelqu'un l'a validée. Les cinq éléments tiennent ou aucun ne tient.

    **Versionnée, jamais modifiée en place.** Corriger une décision crée une
    nouvelle ligne ; l'ancienne reste lisible. C'est le mécanisme déjà retenu
    pour les packs régionaux, et pour la même raison : une purge exécutée hier
    doit rester jugeable sur la règle qui l'autorisait, pas sur celle
    d'aujourd'hui.

    **Le dépôt n'en sème aucune.** Aucune migration, aucun `seed`, aucune
    valeur par défaut n'en crée : elles viendraient d'un droit que ce dépôt ne
    détient pas. Sans décision, la destruction est refusée — et le refus
    conserve.
    """

    __tablename__ = "quote_retention_decisions"
    __table_args__ = (
        CheckConstraint("years >= 0 AND years <= 100", name="ck_retention_years_range"),
        Index("ix_retention_decisions_org", "organization_id", "effective_from"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )

    #: La durée, en années calendaires.
    years: Mapped[int] = mapped_column(Integer, nullable=False)
    #: Le droit sous lequel elle est prise — `BE-WAL`, `FR`, un code de pack.
    #: Deux entreprises soumises à deux droits n'ont pas la même durée, et une
    #: durée sans juridiction ne dit pas de quoi elle parle.
    jurisdiction: Mapped[str] = mapped_column(String(10), nullable=False)
    #: D'où elle sort. Le libellé nomme un TEXTE, pas une personne.
    source_label: Mapped[str] = mapped_column(String(300), nullable=False)
    source_url: Mapped[str | None] = mapped_column(String(500))
    #: Quand la source a été consultée. Sans cette date, « la loi dit » n'est
    #: pas vérifiable : les textes changent.
    source_checked_on: Mapped[date] = mapped_column(Date, nullable=False)
    #: À partir de quand la décision s'applique.
    effective_from: Mapped[date] = mapped_column(Date, nullable=False)

    #: Qui l'a validée, et quand. Un identifiant interne, jamais un nom saisi :
    #: l'utilisateur peut disparaître, la référence reste un identifiant.
    validated_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    validated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)
    note: Mapped[str | None] = mapped_column(Text)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)


class OrganizationPurge(Base):
    """Le registre des destructions d'organisation — et il leur survit.

    Trois raisons de ne PAS le rattacher à `organizations` :

    1. une purge doit laisser une trace après l'organisation, or le journal
       d'audit porte un `organization_id` en CASCADE et meurt donc avec elle ;
    2. la ligne doit rester lisible pour ACHEVER une purge interrompue : elle
       nomme les fichiers restant à retirer du volume ;
    3. un registre qui disparaît avec ce qu'il enregistre n'est pas un registre.

    D'où l'absence de clé étrangère : `organization_id` est une colonne nue.
    C'est délibéré, et c'est la seule table du dépôt dans ce cas.

    **Ce qu'elle ne contient pas**, tout aussi délibérément : aucun texte
    libre. Un identifiant technique, un code de motif pris dans une liste
    fermée, une référence opaque contrainte par la base, des empreintes et des
    chemins de stockage. Le registre prouve qu'une destruction a eu lieu et ce
    qu'elle portait ; il n'offre nulle part où réinscrire ce qu'elle a effacé.
    """

    __tablename__ = "organization_purges"
    __table_args__ = (
        CheckConstraint(
            "status IN ('requested', 'executing', 'rows_deleted', 'completed', 'failed')",
            name="ck_organization_purge_status",
        ),
        CheckConstraint(
            "reason_code IN ('contract_ended', 'subject_request', 'retention_elapsed', "
            "'duplicate_organization', 'demo_reset', 'test_fixture')",
            name="ck_organization_purge_reason",
        ),
        #: Une autorisation n'existe pas sans sa borne, et réciproquement.
        CheckConstraint(
            "(authorized_at IS NULL) = (authorized_until IS NULL)",
            name="ck_organization_purge_window",
        ),
        Index("ix_organization_purges_org", "organization_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    #: Volontairement SANS ForeignKey : voir la note de classe.
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="requested")

    #: Qui a demandé la destruction. L'utilisateur peut lui aussi disparaître :
    #: son identifiant est donc copié, pas référencé.
    requested_by: Mapped[str | None] = mapped_column(String(36))
    requested_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)

    #: La fenêtre d'exécution. `NULL` tant qu'aucune n'a été ouverte, et une
    #: purge sans fenêtre ouverte n'autorise aucune suppression — c'est la
    #: condition que le déclencheur interroge, avec l'horloge de la BASE.
    authorized_at: Mapped[datetime | None] = mapped_column(DateTime)
    authorized_until: Mapped[datetime | None] = mapped_column(DateTime)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime)

    #: Le motif, pris dans `MOTIFS_DE_PURGE`. Une liste fermée, pas une phrase.
    reason_code: Mapped[str] = mapped_column(String(40), nullable=False)
    #: Une référence de dossier, facultative et OPAQUE : ni espace, ni
    #: ponctuation de phrase. La contrainte n'est pas cosmétique — c'est ce qui
    #: empêche d'y écrire « demande de Jean Dupont » sans y penser.
    reference: Mapped[str | None] = mapped_column(String(120))
    #: La durée appliquée et la décision qui l'a fondée, recopiées. Recopiées
    #: et non référencées : la décision vit dans l'organisation, elle meurt
    #: avec elle, et la purge doit rester jugeable après.
    retention_years_applied: Mapped[int] = mapped_column(Integer, nullable=False)
    retention_decision_id: Mapped[str | None] = mapped_column(String(36))

    quote_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    #: Ce qu'il y avait à détruire sur le volume : une entrée par devis, avec sa
    #: clé de stockage et l'empreinte du PDF. C'est ce qui permet de terminer
    #: une purge interrompue sans redécouvrir quoi que ce soit, et de dire
    #: exactement ce qui a été détruit.
    documents: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    files_deleted: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    #: Ce que le volume a refusé de rendre, s'il a refusé. Vide est le cas normal.
    files_failed: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
