"""Persistence model.

Conventions applied to every business table:

* ``id`` is a UUID generated by the application, stable across environments.
* Tenant-owned rows carry ``organization_id`` and every uniqueness constraint
  that could collide between tenants includes it.
* ``created_at`` / ``updated_at`` are UTC and set by the application, not by the
  database, so behaviour is identical on SQLite and PostgreSQL.
* Deletion is logical (``deleted_at``) for anything a user can reference from an
  estimate; audit rows are never deleted.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from decimal import Decimal

from sqlalchemy import JSON as SAJSON
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .db import Amount, Base


def new_id() -> str:
    return str(uuid.uuid4())


def utcnow() -> datetime:
    return datetime.now(UTC).replace(tzinfo=None)


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=utcnow, onupdate=utcnow, nullable=False
    )


# --------------------------------------------------------------------------
# Identity, organisations, permissions
# --------------------------------------------------------------------------


class Organization(TimestampMixin, Base):
    __tablename__ = "organizations"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    legal_name: Mapped[str | None] = mapped_column(String(200))
    company_number: Mapped[str | None] = mapped_column(String(50))
    country_code: Mapped[str] = mapped_column(String(2), nullable=False, default="BE")
    region_code: Mapped[str] = mapped_column(String(10), nullable=False, default="BE-WAL")
    locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    timezone: Mapped[str] = mapped_column(String(50), nullable=False, default="Europe/Brussels")
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)

    settings: Mapped[OrganizationSettings] = relationship(
        back_populates="organization", uselist=False, cascade="all, delete-orphan"
    )


class OrganizationSettings(TimestampMixin, Base):
    """Company rules that drive the deterministic engine.

    These values are copied into a frozen estimate version; changing them later
    never rewrites a frozen figure.
    """

    __tablename__ = "organization_settings"

    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), primary_key=True
    )
    rounding_scale: Mapped[int] = mapped_column(Integer, nullable=False, default=2)
    rounding_mode: Mapped[str] = mapped_column(String(20), nullable=False, default="half_up")
    unit_price_scale: Mapped[int] = mapped_column(Integer, nullable=False, default=2)

    site_overheads_rate: Mapped[Decimal] = mapped_column(
        Amount, nullable=False, default=Decimal("0")
    )
    site_overheads_base: Mapped[str] = mapped_column(
        String(30), nullable=False, default="direct_cost"
    )
    general_overheads_rate: Mapped[Decimal] = mapped_column(
        Amount, nullable=False, default=Decimal("0")
    )
    general_overheads_base: Mapped[str] = mapped_column(
        String(30), nullable=False, default="direct_plus_site"
    )
    contingency_rate: Mapped[Decimal] = mapped_column(Amount, nullable=False, default=Decimal("0"))
    contingency_base: Mapped[str] = mapped_column(
        String(30), nullable=False, default="running_total"
    )
    margin_rate: Mapped[Decimal] = mapped_column(Amount, nullable=False, default=Decimal("0"))
    margin_method: Mapped[str] = mapped_column(String(20), nullable=False, default="on_cost")

    missing_price_policy: Mapped[str] = mapped_column(String(10), nullable=False, default="block")
    quote_number_pattern: Mapped[str] = mapped_column(
        String(60), nullable=False, default="DEV-{year}-{sequence:04d}"
    )
    show_internal_costs_in_client_pdf: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )
    ai_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    organization: Mapped[Organization] = relationship(back_populates="settings")


class TaxRateRow(TimestampMixin, Base):
    __tablename__ = "tax_rates"
    __table_args__ = (
        UniqueConstraint("organization_id", "code", "applies_from", name="uq_tax_org_code_from"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    code: Mapped[str] = mapped_column(String(30), nullable=False)
    label: Mapped[str] = mapped_column(String(120), nullable=False)
    rate: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    applies_from: Mapped[datetime | None] = mapped_column(Date)
    applies_to: Mapped[datetime | None] = mapped_column(Date)
    is_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    source: Mapped[str | None] = mapped_column(String(255))


class User(TimestampMixin, Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    full_name: Mapped[str] = mapped_column(String(200), nullable=False)
    locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    memberships: Mapped[list[Membership]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class ExternalIdentity(TimestampMixin, Base):
    """Le lien entre un compte local et une identité chez un fournisseur.

    La clé est le couple ``(issuer, subject)``, que le fournisseur garantit
    immuable. L'adresse électronique ne sert qu'une fois, à créer ce lien : elle
    est réattribuable et usurpable, et s'y fier durablement permettrait de
    reprendre un compte en obtenant l'adresse chez le fournisseur.

    ``email_at_link`` conserve l'adresse telle qu'elle était au moment de la
    liaison. Elle ne sert à rien d'autre qu'à retrouver plus tard *pourquoi*
    ce lien existe — un audit, pas une identification.

    Un utilisateur peut porter plusieurs identités (deux fournisseurs), mais une
    identité donnée n'appartient qu'à un utilisateur : l'unicité porte sur
    ``(issuer, subject)``.
    """

    __tablename__ = "external_identities"
    __table_args__ = (
        UniqueConstraint("issuer", "subject", name="uq_external_identity_issuer_subject"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    issuer: Mapped[str] = mapped_column(String(255), nullable=False)
    subject: Mapped[str] = mapped_column(String(255), nullable=False)
    email_at_link: Mapped[str | None] = mapped_column(String(255))
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime)


class LoginTransaction(Base):
    """Une demande de connexion en cours, du départ au retour du navigateur.

    Elle vit en base et non en mémoire de processus : l'utilisateur peut partir
    depuis une instance de l'API et revenir sur une autre, qui ne connaîtrait
    rien d'un dictionnaire local. C'est la condition pour tourner à plus d'une
    instance.

    ``consumed_at`` fait du rejeu un refus par l'état, pas par une convention :
    une transaction déjà servie ne peut plus l'être, quelle que soit la
    fenêtre de temps restante.

    ``login_code`` est le code opaque rendu au navigateur à la place du jeton.
    Un JWT dans une URL de retour finit dans l'historique, les journaux du
    proxy et l'en-tête ``Referer`` ; un code court, à usage unique et échangé
    contre la session, non.
    """

    __tablename__ = "login_transactions"
    __table_args__ = (
        UniqueConstraint("state", name="uq_login_transaction_state"),
        UniqueConstraint("login_code", name="uq_login_transaction_code"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    state: Mapped[str] = mapped_column(String(64), nullable=False)
    nonce: Mapped[str] = mapped_column(String(64), nullable=False)
    code_verifier: Mapped[str] = mapped_column(String(128), nullable=False)
    redirect_uri: Mapped[str] = mapped_column(String(500), nullable=False)
    #: Où renvoyer l'utilisateur dans l'application après la connexion.
    return_to: Mapped[str | None] = mapped_column(String(500))
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    #: Horodatage de la consommation du `state`, au retour du fournisseur.
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime)
    #: Rempli une fois l'identité vérifiée, puis effacé à l'échange.
    login_code: Mapped[str | None] = mapped_column(String(64))
    login_code_expires_at: Mapped[datetime | None] = mapped_column(DateTime)
    user_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    organization_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("organizations.id"))


class Membership(TimestampMixin, Base):
    """A user's role inside one organisation. A user may belong to several."""

    __tablename__ = "memberships"
    __table_args__ = (
        UniqueConstraint("user_id", "organization_id", name="uq_membership_user_org"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(String(40), nullable=False, default="estimator")
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    user: Mapped[User] = relationship(back_populates="memberships")


# --------------------------------------------------------------------------
# Country / region packs
# --------------------------------------------------------------------------


class RegionProfile(TimestampMixin, Base):
    """A versioned country/region pack.

    Global (not tenant-owned): the pack describes public rules, an organisation
    only *selects* one. ``terminology`` and ``rules`` stay JSON on purpose —
    what a pack needs to declare differs per country and must not require a
    migration for each new one.
    """

    __tablename__ = "region_profiles"
    __table_args__ = (UniqueConstraint("code", "version", name="uq_region_code_version"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    country_code: Mapped[str] = mapped_column(String(2), nullable=False, index=True)
    code: Mapped[str] = mapped_column(String(10), nullable=False)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    version: Mapped[str] = mapped_column(String(20), nullable=False, default="2026.1")
    effective_from: Mapped[datetime | None] = mapped_column(Date)
    default_locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    locales: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    default_currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    terminology: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    rules: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    sources: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    disclaimer: Mapped[str | None] = mapped_column(Text)


# --------------------------------------------------------------------------
# Projects
# --------------------------------------------------------------------------


class Project(TimestampMixin, Base):
    __tablename__ = "projects"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_projects_id_organization"),
        UniqueConstraint("organization_id", "reference", name="uq_project_org_reference"),
        Index("ix_projects_org_status", "organization_id", "status"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    reference: Mapped[str] = mapped_column(String(60), nullable=False)
    client_reference: Mapped[str | None] = mapped_column(String(120))
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    client_name: Mapped[str | None] = mapped_column(String(200))
    address: Mapped[str | None] = mapped_column(String(255))
    postal_code: Mapped[str | None] = mapped_column(String(20))
    city: Mapped[str | None] = mapped_column(String(120))
    country_code: Mapped[str] = mapped_column(String(2), nullable=False, default="BE")
    region_code: Mapped[str] = mapped_column(String(10), nullable=False, default="BE-WAL")
    latitude: Mapped[Decimal | None] = mapped_column(Amount)
    longitude: Mapped[Decimal | None] = mapped_column(Amount)
    market_type: Mapped[str | None] = mapped_column(String(60))
    work_categories: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    submission_deadline: Mapped[datetime | None] = mapped_column(DateTime)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="draft")
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


# --------------------------------------------------------------------------
# Documents and human-reviewed extraction
# --------------------------------------------------------------------------


class Document(TimestampMixin, Base):
    """Logical document owned by exactly one project and organisation."""

    __tablename__ = "documents"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name="fk_documents_org_project",
            ondelete="CASCADE",
        ),
        UniqueConstraint("organization_id", "id", name="uq_document_org_id"),
        CheckConstraint("status IN ('active','archived')", name="ck_document_status"),
        CheckConstraint("length(trim(title)) > 0", name="ck_document_title_nonempty"),
        Index("ix_documents_org_project", "organization_id", "project_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    project_id: Mapped[str] = mapped_column(String(36), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class DocumentRevision(TimestampMixin, Base):
    """Immutable original once ``published_at`` is set.

    Database triggers installed by the migration enforce the immutability for
    direct SQL as well as ORM writes. Pipeline progress lives in
    :class:`DocumentStepRun`, never in this row.
    """

    __tablename__ = "document_revisions"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "document_id"],
            ["documents.organization_id", "documents.id"],
            name="fk_document_revisions_org_document",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "organization_id",
            "document_id",
            "revision_number",
            name="uq_document_revision_number",
        ),
        UniqueConstraint("organization_id", "id", name="uq_document_revision_org_id"),
        CheckConstraint("revision_number > 0", name="ck_document_revision_number_positive"),
        CheckConstraint("byte_size > 0", name="ck_document_revision_byte_size_positive"),
        CheckConstraint("length(sha256) = 64", name="ck_document_revision_sha256_length"),
        CheckConstraint(
            "length(trim(media_type)) > 0 AND length(trim(storage_key)) > 0 "
            "AND length(trim(original_filename)) > 0",
            name="ck_document_revision_required_text",
        ),
        CheckConstraint("status IN ('draft','published')", name="ck_document_revision_status"),
        CheckConstraint(
            "(status != 'draft' OR published_at IS NULL) AND "
            "(status != 'published' OR published_at IS NOT NULL)",
            name="ck_document_revision_publication",
        ),
        Index("ix_document_revisions_org_document", "organization_id", "document_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    document_id: Mapped[str] = mapped_column(String(36), nullable=False)
    revision_number: Mapped[int] = mapped_column(Integer, nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False)
    #: Le type lu dans les octets. C'est lui qui fait foi et qui est re-servi.
    media_type: Mapped[str] = mapped_column(String(120), nullable=False)
    #: Le type qu'annonçait le client. Gardé à part, jamais utilisé pour
    #: décider : il ne sert qu'à expliquer un refus ou une incohérence.
    declared_media_type: Mapped[str | None] = mapped_column(String(120))
    storage_key: Mapped[str] = mapped_column(String(512), nullable=False)
    original_filename: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    published_at: Mapped[datetime | None] = mapped_column(DateTime)
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


class DocumentStepRun(TimestampMixin, Base):
    """Idempotent state of one pipeline step for one immutable revision."""

    __tablename__ = "document_step_runs"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "revision_id"],
            ["document_revisions.organization_id", "document_revisions.id"],
            name="fk_document_step_runs_org_revision",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "organization_id",
            "revision_id",
            "step",
            "pipeline_version",
            "prompt_version",
            "model_version",
            name="uq_document_step_run_idempotence",
        ),
        CheckConstraint(
            "step IN ('receive_security','detection','native_text','ocr','tables',"
            "'segmentation','classification','structured_extraction','indexing',"
            "'consistency','human_review')",
            name="ck_document_step_run_step",
        ),
        CheckConstraint(
            "status IN ('pending','running','succeeded','failed')",
            name="ck_document_step_run_status",
        ),
        CheckConstraint("attempt >= 1", name="ck_document_step_run_attempt"),
        CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name="ck_document_step_run_duration",
        ),
        CheckConstraint(
            "status != 'failed' OR (error_code IS NOT NULL AND length(trim(error_code)) > 0)",
            name="ck_document_step_run_failure_code",
        ),
        CheckConstraint(
            "length(trim(pipeline_version)) > 0 AND length(trim(prompt_version)) > 0 "
            "AND length(trim(model_version)) > 0",
            name="ck_document_step_run_versions_nonempty",
        ),
        Index("ix_document_step_runs_org_revision", "organization_id", "revision_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    revision_id: Mapped[str] = mapped_column(String(36), nullable=False)
    step: Mapped[str] = mapped_column(String(40), nullable=False)
    pipeline_version: Mapped[str] = mapped_column(String(80), nullable=False)
    prompt_version: Mapped[str] = mapped_column(String(80), nullable=False, default="none")
    model_version: Mapped[str] = mapped_column(String(80), nullable=False, default="none")
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    attempt: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    started_at: Mapped[datetime | None] = mapped_column(DateTime)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime)
    duration_ms: Mapped[int | None] = mapped_column(Integer)
    error_code: Mapped[str | None] = mapped_column(String(80))
    error_summary: Mapped[str | None] = mapped_column(String(255))


class SourceCitation(TimestampMixin, Base):
    """Resolvable source location; never a free-form “see page” string."""

    __tablename__ = "source_citations"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "revision_id"],
            ["document_revisions.organization_id", "document_revisions.id"],
            name="fk_source_citations_org_revision",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "organization_id",
            "revision_id",
            "id",
            name="uq_source_citation_org_revision_id",
        ),
        CheckConstraint("page >= 1", name="ck_source_citation_page"),
        CheckConstraint("char_start >= 0", name="ck_source_citation_char_start"),
        CheckConstraint("char_end > char_start", name="ck_source_citation_char_range"),
        CheckConstraint(
            "x0 >= 0 AND x0 <= 1 AND y0 >= 0 AND y0 <= 1 AND "
            "x1 >= 0 AND x1 <= 1 AND y1 >= 0 AND y1 <= 1 AND "
            "x0 < x1 AND y0 < y1",
            name="ck_source_citation_bbox",
        ),
        CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name="ck_source_citation_confidence",
        ),
        CheckConstraint(
            "length(trim(extractor)) > 0",
            name="ck_source_citation_extractor_nonempty",
        ),
        Index("ix_source_citations_org_revision", "organization_id", "revision_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    revision_id: Mapped[str] = mapped_column(String(36), nullable=False)
    page: Mapped[int] = mapped_column(Integer, nullable=False)
    char_start: Mapped[int] = mapped_column(Integer, nullable=False)
    char_end: Mapped[int] = mapped_column(Integer, nullable=False)
    x0: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    y0: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    x1: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    y1: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    sheet: Mapped[str | None] = mapped_column(String(120))
    layer: Mapped[str | None] = mapped_column(String(120))
    object_id: Mapped[str | None] = mapped_column(String(120))
    extractor: Mapped[str] = mapped_column(String(120), nullable=False)
    confidence: Mapped[Decimal] = mapped_column(Amount, nullable=False)


class ExtractionProposal(TimestampMixin, Base):
    """Machine output awaiting a separate append-only human decision."""

    __tablename__ = "extraction_proposals"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "revision_id", "citation_id"],
            [
                "source_citations.organization_id",
                "source_citations.revision_id",
                "source_citations.id",
            ],
            name="fk_extraction_proposals_org_revision_citation",
            ondelete="CASCADE",
        ),
        UniqueConstraint("organization_id", "id", name="uq_extraction_proposal_org_id"),
        CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name="ck_extraction_proposal_confidence",
        ),
        CheckConstraint(
            "status IN ('proposed','accepted','corrected','rejected')",
            name="ck_extraction_proposal_status",
        ),
        CheckConstraint(
            "length(trim(schema_name)) > 0 AND length(trim(schema_version)) > 0 "
            "AND length(trim(pipeline_version)) > 0 "
            "AND length(trim(prompt_version)) > 0 "
            "AND length(trim(model_version)) > 0",
            name="ck_extraction_proposal_versions_nonempty",
        ),
        Index("ix_extraction_proposals_org_revision", "organization_id", "revision_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    revision_id: Mapped[str] = mapped_column(String(36), nullable=False)
    citation_id: Mapped[str] = mapped_column(String(36), nullable=False)
    schema_name: Mapped[str] = mapped_column(String(120), nullable=False)
    schema_version: Mapped[str] = mapped_column(String(80), nullable=False)
    value: Mapped[dict] = mapped_column(SAJSON, nullable=False)
    confidence: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    pipeline_version: Mapped[str] = mapped_column(String(80), nullable=False)
    prompt_version: Mapped[str] = mapped_column(String(80), nullable=False)
    model_version: Mapped[str] = mapped_column(String(80), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="proposed")


class ValidationDecision(Base):
    """Append-only record of one human acceptance, correction or rejection."""

    __tablename__ = "validation_decisions"
    __table_args__ = (
        ForeignKeyConstraint(
            ["organization_id", "proposal_id"],
            ["extraction_proposals.organization_id", "extraction_proposals.id"],
            name="fk_validation_decisions_org_proposal",
            ondelete="RESTRICT",
        ),
        ForeignKeyConstraint(
            ["actor_user_id", "organization_id"],
            ["memberships.user_id", "memberships.organization_id"],
            name="fk_validation_decisions_actor_membership",
            ondelete="RESTRICT",
        ),
        CheckConstraint(
            "decision IN ('accepted','corrected','rejected')",
            name="ck_validation_decision_value",
        ),
        CheckConstraint(
            "length(trim(reason)) > 0",
            name="ck_validation_decision_reason",
        ),
        CheckConstraint(
            "(decision != 'corrected' OR (before_value IS NOT NULL AND after_value IS NOT NULL)) "
            "AND (decision NOT IN ('accepted','rejected') OR "
            "(before_value IS NULL AND after_value IS NULL))",
            name="ck_validation_decision_correction_payload",
        ),
        Index("ix_validation_decisions_org_proposal", "organization_id", "proposal_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    proposal_id: Mapped[str] = mapped_column(String(36), nullable=False)
    actor_user_id: Mapped[str] = mapped_column(String(36), nullable=False)
    decision: Mapped[str] = mapped_column(String(20), nullable=False)
    reason: Mapped[str] = mapped_column(Text, nullable=False)
    before_value: Mapped[dict | None] = mapped_column(SAJSON(none_as_null=True))
    after_value: Mapped[dict | None] = mapped_column(SAJSON(none_as_null=True))
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)


# --------------------------------------------------------------------------
# Price library
# --------------------------------------------------------------------------


class PriceBook(TimestampMixin, Base):
    __tablename__ = "price_books"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_price_books_id_organization"),
        UniqueConstraint("organization_id", "name", name="uq_pricebook_org_name"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(160), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    is_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class PriceBookVersion(TimestampMixin, Base):
    """A published version is immutable; drafts are where imports land."""

    __tablename__ = "price_book_versions"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_price_book_versions_id_organization"),
        ForeignKeyConstraint(
            ["price_book_id", "organization_id"],
            ["price_books.id", "price_books.organization_id"],
            name="fk_price_book_versions_price_book_tenant",
            ondelete="CASCADE",
        ),
        UniqueConstraint("price_book_id", "version_number", name="uq_pbv_book_number"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("price_books.id", ondelete="CASCADE"), nullable=False, index=True
    )
    version_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    label: Mapped[str | None] = mapped_column(String(160))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    published_at: Mapped[datetime | None] = mapped_column(DateTime)
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


class PriceItem(TimestampMixin, Base):
    __tablename__ = "price_items"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_price_items_id_organization"),
        ForeignKeyConstraint(
            ["price_book_version_id", "organization_id"],
            ["price_book_versions.id", "price_book_versions.organization_id"],
            name="fk_price_items_price_book_version_tenant",
            ondelete="CASCADE",
        ),
        CheckConstraint(
            "resource_kind IN ('material','labor','equipment','transport',"
            "'disposal','subcontract','other')",
            name="ck_price_item_resource_kind",
        ),
        CheckConstraint(
            "status IN ('active','draft','archived','superseded')",
            name="ck_price_item_status",
        ),
        CheckConstraint(
            "confidence IN ('declared','quoted','contracted','estimated')",
            name="ck_price_item_confidence",
        ),
        CheckConstraint(
            "valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from",
            name="ck_price_item_validity_range",
        ),
        CheckConstraint(
            "lead_time_days IS NULL OR (lead_time_days >= 0 AND lead_time_days <= 3650)",
            name="ck_price_item_lead_time",
        ),
        UniqueConstraint("price_book_version_id", "code", name="uq_priceitem_version_code"),
        Index("ix_price_items_org_family", "organization_id", "family"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("price_book_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    code: Mapped[str] = mapped_column(String(60), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    family: Mapped[str | None] = mapped_column(String(60))
    resource_kind: Mapped[str] = mapped_column(String(30), nullable=False, default="material")
    unit_code: Mapped[str] = mapped_column(String(12), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    supplier_name: Mapped[str | None] = mapped_column(String(200))
    region_code: Mapped[str | None] = mapped_column(String(10))
    valid_from: Mapped[datetime | None] = mapped_column(Date)
    valid_to: Mapped[datetime | None] = mapped_column(Date)
    min_quantity: Mapped[Decimal | None] = mapped_column(Amount)
    lead_time_days: Mapped[int | None] = mapped_column(Integer)
    source: Mapped[str | None] = mapped_column(String(255))
    conditions: Mapped[str | None] = mapped_column(Text)
    indexation: Mapped[str | None] = mapped_column(String(120))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    confidence: Mapped[str] = mapped_column(String(20), nullable=False, default="declared")
    is_demo_data: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    notes: Mapped[str | None] = mapped_column(Text)


class CompositePriceRow(TimestampMixin, Base):
    """A reusable sub-detail (sous-détail de prix)."""

    __tablename__ = "composite_prices"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        ForeignKeyConstraint(
            ["price_book_version_id", "organization_id"],
            ["price_book_versions.id", "price_book_versions.organization_id"],
            name="fk_composite_prices_price_book_version_tenant",
            ondelete="CASCADE",
        ),
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_composite_prices_id_organization"),
        UniqueConstraint("price_book_version_id", "code", name="uq_composite_version_code"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("price_book_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    code: Mapped[str] = mapped_column(String(60), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    unit_code: Mapped[str] = mapped_column(String(12), nullable=False)
    notes: Mapped[str | None] = mapped_column(Text)
    is_demo_data: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    components: Mapped[list[CompositeComponentRow]] = relationship(
        back_populates="composite",
        cascade="all, delete-orphan",
        order_by="CompositeComponentRow.sort_index",
        # Deux chemins de clé relient désormais ces deux tables : la clé simple
        # `composite_price_id`, et la clé composite qui lui adjoint
        # `organization_id`. SQLAlchemy refuse de choisir — il lève
        # `AmbiguousForeignKeysError` — et il a raison de refuser : c'est à
        # nous de dire lequel porte la relation.
        foreign_keys="CompositeComponentRow.composite_price_id",
    )


class CompositeComponentRow(TimestampMixin, Base):
    """One row of a sub-detail.

    A single wide table with nullable columns keyed by ``component_type`` keeps
    the sub-detail readable in one query. Which columns are required for which
    type is validated in :mod:`metreo_api.services.composites`, and the
    check constraint below stops an unknown type from being stored at all.
    """

    __tablename__ = "composite_components"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        ForeignKeyConstraint(
            ["composite_price_id", "organization_id"],
            ["composite_prices.id", "composite_prices.organization_id"],
            name="fk_composite_components_composite_price_tenant",
            ondelete="CASCADE",
        ),
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        ForeignKeyConstraint(
            ["price_item_id", "organization_id"],
            ["price_items.id", "price_items.organization_id"],
            name="fk_composite_components_price_item_tenant",
            ondelete="SET NULL (price_item_id)",
        ),
        CheckConstraint(
            "component_type IN ('consumption','output_rate','rotation','lump_sum')",
            name="ck_composite_component_type",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    composite_price_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("composite_prices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    sort_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    component_type: Mapped[str] = mapped_column(String(20), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    resource_kind: Mapped[str] = mapped_column(String(30), nullable=False, default="other")
    price_item_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("price_items.id", ondelete="SET NULL")
    )

    # consumption
    consumption: Mapped[Decimal | None] = mapped_column(Amount)
    resource_unit_code: Mapped[str | None] = mapped_column(String(12))
    unit_price: Mapped[Decimal | None] = mapped_column(Amount)
    loss_ratio: Mapped[Decimal | None] = mapped_column(Amount)
    convert_boq_quantity: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    density_value: Mapped[Decimal | None] = mapped_column(Amount)
    density_source: Mapped[str | None] = mapped_column(String(255))

    # output rate
    output_rate: Mapped[Decimal | None] = mapped_column(Amount)
    hourly_rate: Mapped[Decimal | None] = mapped_column(Amount)
    crew_size: Mapped[Decimal | None] = mapped_column(Amount)

    # rotation
    payload_value: Mapped[Decimal | None] = mapped_column(Amount)
    payload_unit_code: Mapped[str | None] = mapped_column(String(12))
    cost_per_rotation: Mapped[Decimal | None] = mapped_column(Amount)
    round_up: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    distance_km: Mapped[Decimal | None] = mapped_column(Amount)
    rate_per_km: Mapped[Decimal | None] = mapped_column(Amount)

    # lump sum
    lump_sum_amount: Mapped[Decimal | None] = mapped_column(Amount)

    composite: Mapped[CompositePriceRow] = relationship(
        back_populates="components",
        foreign_keys="CompositeComponentRow.composite_price_id",
    )


# --------------------------------------------------------------------------
# CSV import staging
# --------------------------------------------------------------------------


class ImportBatch(TimestampMixin, Base):
    """A previewed import. Nothing reaches ``price_items`` before ``commit``."""

    __tablename__ = "import_batches"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        ForeignKeyConstraint(
            ["price_book_version_id", "organization_id"],
            ["price_book_versions.id", "price_book_versions.organization_id"],
            name="fk_import_batches_price_book_version_tenant",
            ondelete="CASCADE",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("price_book_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="previewed")
    strategy: Mapped[str] = mapped_column(String(20), nullable=False, default="create")
    row_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    valid_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    error_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    duplicate_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    column_mapping: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    committed_at: Mapped[datetime | None] = mapped_column(DateTime)

    rows: Mapped[list[ImportBatchRow]] = relationship(
        back_populates="batch", cascade="all, delete-orphan", order_by="ImportBatchRow.line_number"
    )


class ImportBatchRow(Base):
    __tablename__ = "import_batch_rows"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    batch_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("import_batches.id", ondelete="CASCADE"), nullable=False, index=True
    )
    line_number: Mapped[int] = mapped_column(Integer, nullable=False)
    raw: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    normalized: Mapped[dict | None] = mapped_column(SAJSON)
    is_valid: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    is_duplicate: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    errors: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)

    batch: Mapped[ImportBatch] = relationship(back_populates="rows")


# --------------------------------------------------------------------------
# Bill of quantities
# --------------------------------------------------------------------------


class BillOfQuantities(TimestampMixin, Base):
    __tablename__ = "bills_of_quantities"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        UniqueConstraint("id", "organization_id", name="uq_bills_of_quantities_id_organization"),
        ForeignKeyConstraint(
            ["project_id", "organization_id"],
            ["projects.id", "projects.organization_id"],
            name="fk_bills_of_quantities_project_tenant",
            ondelete="CASCADE",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    source: Mapped[str] = mapped_column(String(20), nullable=False, default="manual")
    revision: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    notes: Mapped[str | None] = mapped_column(Text)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class BoqItem(TimestampMixin, Base):
    __tablename__ = "boq_items"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        UniqueConstraint("id", "organization_id", name="uq_boq_items_id_organization"),
        ForeignKeyConstraint(
            ["parent_id", "organization_id"],
            ["boq_items.id", "boq_items.organization_id"],
            name="fk_boq_items_parent_tenant",
            ondelete="CASCADE",
        ),
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        ForeignKeyConstraint(
            ["boq_id", "organization_id"],
            ["bills_of_quantities.id", "bills_of_quantities.organization_id"],
            name="fk_boq_items_boq_tenant",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["price_item_id", "organization_id"],
            ["price_items.id", "price_items.organization_id"],
            name="fk_boq_items_price_item_tenant",
            ondelete="SET NULL (price_item_id)",
        ),
        ForeignKeyConstraint(
            ["composite_price_id", "organization_id"],
            ["composite_prices.id", "composite_prices.organization_id"],
            name="fk_boq_items_composite_price_tenant",
            ondelete="SET NULL (composite_price_id)",
        ),
        CheckConstraint(
            "price_item_id IS NULL OR composite_price_id IS NULL",
            name="ck_boq_item_single_price_source",
        ),
        UniqueConstraint("boq_id", "position", name="uq_boqitem_boq_position"),
        CheckConstraint(
            "kind IN ('section','item','option','variant','provisional')",
            name="ck_boq_item_kind",
        ),
        CheckConstraint(
            "status IN ('proposed','verified','approved','rejected')",
            name="ck_boq_item_status",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    boq_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("bills_of_quantities.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    parent_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("boq_items.id", ondelete="CASCADE")
    )
    sort_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    position: Mapped[str] = mapped_column(String(40), nullable=False)
    code: Mapped[str | None] = mapped_column(String(60))
    designation: Mapped[str] = mapped_column(Text, nullable=False)
    unit_code: Mapped[str] = mapped_column(String(12), nullable=False, default="fft")
    quantity: Mapped[Decimal] = mapped_column(Amount, nullable=False, default=Decimal("0"))
    kind: Mapped[str] = mapped_column(String(20), nullable=False, default="item")
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="proposed")
    formula: Mapped[str | None] = mapped_column(Text)
    client_quantity: Mapped[Decimal | None] = mapped_column(Amount)
    notes: Mapped[str | None] = mapped_column(Text)
    price_item_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("price_items.id", ondelete="SET NULL")
    )
    composite_price_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("composite_prices.id", ondelete="SET NULL")
    )


# --------------------------------------------------------------------------
# Estimates
# --------------------------------------------------------------------------


class Estimate(TimestampMixin, Base):
    __tablename__ = "estimates"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        UniqueConstraint("id", "organization_id", name="uq_estimates_id_organization"),
        ForeignKeyConstraint(
            ["project_id", "organization_id"],
            ["projects.id", "projects.organization_id"],
            name="fk_estimates_project_tenant",
            ondelete="CASCADE",
        ),
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle de ces
        # clés composites appartient aux migrations et non aux modèles : elle
        # diffère d'un moteur à l'autre. Sur PostgreSQL, la révision
        # `b4f2c7d81a05` fait refléter à chaque composite l'action de la clé
        # simple qu'elle double — `SET NULL (colonne_enfant)` plutôt qu'un
        # `SET NULL` nu, qui viderait aussi `organization_id`, NOT NULL — afin
        # que le résultat d'une suppression ne dépende plus de l'ordre de
        # création des contraintes. SQLite n'en a pas besoin : mesuré, les deux
        # ordres y donnent le même résultat.
        ForeignKeyConstraint(
            ["boq_id", "organization_id"],
            ["bills_of_quantities.id", "bills_of_quantities.organization_id"],
            name="fk_estimates_boq_tenant",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["price_book_version_id", "organization_id"],
            ["price_book_versions.id", "price_book_versions.organization_id"],
            name="fk_estimates_price_book_version_tenant",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    boq_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("bills_of_quantities.id", ondelete="CASCADE"), nullable=False
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("price_book_versions.id"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class EstimateVersion(TimestampMixin, Base):
    """A frozen version stores the computed result *and* its inputs.

    ``snapshot`` holds the resolved lines, the price book version identifier,
    the markup policy and the tax rates that were in force. Recomputing it later
    reproduces the same numbers even if the library has moved on, which is what
    acceptance scenarios 6 and 7 require.
    """

    __tablename__ = "estimate_versions"
    __table_args__ = (
        # Frontière multi-tenant tenue par la base : l'enfant ne peut pointer
        # qu'un parent de SA propre organisation. L'action référentielle reflète
        # celle de la clé simple que double chaque composite — sans ce reflet, le
        # résultat d'une suppression dépendrait de l'ordre de création des
        # contraintes (révision `b4f2c7d81a05`).
        ForeignKeyConstraint(
            ["estimate_id", "organization_id"],
            ["estimates.id", "estimates.organization_id"],
            name="fk_estimate_versions_estimate_tenant",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["price_book_version_id", "organization_id"],
            ["price_book_versions.id", "price_book_versions.organization_id"],
            name="fk_estimate_versions_price_book_version_tenant",
        ),
        UniqueConstraint("estimate_id", "version_number", name="uq_estimateversion_number"),
        CheckConstraint(
            "status IN ('draft','frozen','superseded')", name="ck_estimate_version_status"
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    estimate_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("estimates.id", ondelete="CASCADE"), nullable=False, index=True
    )
    version_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    label: Mapped[str | None] = mapped_column(String(200))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    price_book_version_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("price_book_versions.id"), nullable=False
    )
    markup: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    taxes: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    rounding: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    missing_price_policy: Mapped[str] = mapped_column(String(10), nullable=False, default="block")
    snapshot: Mapped[dict | None] = mapped_column(SAJSON)
    snapshot_sha256: Mapped[str | None] = mapped_column(String(64))
    #: Totaux **bruts**, non arrondis, tels que le moteur les a produits. Ce
    #: sont eux qui servent aux calculs internes et aux comparaisons ; ils ne
    #: sont pas ce que le devis imprime.
    total_selling_price_ht: Mapped[Decimal | None] = mapped_column(Amount)
    total_ttc: Mapped[Decimal | None] = mapped_column(Amount)
    #: Totaux **du document**, figés au gel : exactement les nombres que le
    #: devis remis au client porte, sous la convention « le document
    #: s'additionne » (voir `docs/ARRONDI_DES_DOCUMENTS.md`).
    #:
    #: Deux colonnes distinctes plutôt qu'une réinterprétation des précédentes :
    #: brut et imprimé ne coïncident pas, et une colonne qui aurait porté les
    #: deux sens selon la date de la ligne aurait été un piège permanent.
    #:
    #: `NULL` a un sens précis et unique : *le total documentaire de cette
    #: version gelée n'a pas pu être reconstruit*. Il n'est jamais remplacé en
    #: silence par l'arrondi du brut — un lecteur doit savoir qu'il ne dispose
    #: pas du nombre imprimé. Une version brouillon n'en porte pas non plus :
    #: son document se recalcule à la demande.
    document_total_ht: Mapped[Decimal | None] = mapped_column(Amount)
    document_total_ttc: Mapped[Decimal | None] = mapped_column(Amount)
    frozen_at: Mapped[datetime | None] = mapped_column(DateTime)
    frozen_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


# --------------------------------------------------------------------------
# Audit
# --------------------------------------------------------------------------


class AuditEvent(Base):
    """Append-only journal with a per-organisation hash chain.

    ``previous_hash`` links each row to the one before it inside the same
    organisation. Deleting or editing a row breaks the chain, which
    ``/audit/verify`` detects. This is tamper-evidence, not tamper-proofing —
    stated as such in the security threat model.
    """

    __tablename__ = "audit_events"
    __table_args__ = (
        Index("ix_audit_org_occurred", "organization_id", "occurred_at"),
        UniqueConstraint("organization_id", "sequence", name="uq_audit_org_sequence"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    sequence: Mapped[int] = mapped_column(Integer, nullable=False)
    occurred_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)
    actor_user_id: Mapped[str | None] = mapped_column(String(36))
    actor_email: Mapped[str | None] = mapped_column(String(255))
    action: Mapped[str] = mapped_column(String(80), nullable=False)
    object_type: Mapped[str] = mapped_column(String(60), nullable=False)
    object_id: Mapped[str | None] = mapped_column(String(36))
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    request_id: Mapped[str | None] = mapped_column(String(64))
    #: Version du schéma de hash sous laquelle l'événement a été scellé. Une
    #: constante Python seule ne permettrait pas de revérifier durablement des
    #: événements créés sous plusieurs versions : la vérification lirait le code
    #: d'aujourd'hui pour juger un scellé d'hier.
    #: Renseigné explicitement par `audit.record()`. Pas de valeur par défaut :
    #: un défaut silencieux à 1 marquerait un événement scellé en v2 comme v1,
    #: et le rendrait invérifiable.
    hash_schema_version: Mapped[int] = mapped_column(Integer, nullable=False)
    previous_hash: Mapped[str | None] = mapped_column(String(64))
    hash: Mapped[str] = mapped_column(String(64), nullable=False)
