"""Persistence model.

Conventions applied to every business table:

* ``id`` is a UUID generated by the application, stable across environments.
* Tenant-owned rows carry ``organization_id`` and every uniqueness constraint
  that could collide between tenants includes it.
* ``created_at`` / ``updated_at`` are UTC and set by the application, not by the
  database, so behaviour is identical on SQLite and PostgreSQL.
* Deletion is logical (``deleted_at``) for anything a user can reference from an
  estimate; audit rows are never deleted.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from decimal import Decimal

from sqlalchemy import JSON as SAJSON
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .db import Amount, Base


def new_id() -> str:
    return str(uuid.uuid4())


def utcnow() -> datetime:
    return datetime.now(UTC).replace(tzinfo=None)


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=utcnow, onupdate=utcnow, nullable=False
    )


# --------------------------------------------------------------------------
# Identity, organisations, permissions
# --------------------------------------------------------------------------


class Organization(TimestampMixin, Base):
    __tablename__ = "organizations"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    legal_name: Mapped[str | None] = mapped_column(String(200))
    company_number: Mapped[str | None] = mapped_column(String(50))
    country_code: Mapped[str] = mapped_column(String(2), nullable=False, default="BE")
    region_code: Mapped[str] = mapped_column(String(10), nullable=False, default="BE-WAL")
    locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    timezone: Mapped[str] = mapped_column(String(50), nullable=False, default="Europe/Brussels")
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)

    settings: Mapped[OrganizationSettings] = relationship(
        back_populates="organization", uselist=False, cascade="all, delete-orphan"
    )


class OrganizationSettings(TimestampMixin, Base):
    """Company rules that drive the deterministic engine.

    These values are copied into a frozen estimate version; changing them later
    never rewrites a frozen figure.
    """

    __tablename__ = "organization_settings"

    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), primary_key=True
    )
    rounding_scale: Mapped[int] = mapped_column(Integer, nullable=False, default=2)
    rounding_mode: Mapped[str] = mapped_column(String(20), nullable=False, default="half_up")
    unit_price_scale: Mapped[int] = mapped_column(Integer, nullable=False, default=2)

    site_overheads_rate: Mapped[Decimal] = mapped_column(
        Amount, nullable=False, default=Decimal("0")
    )
    site_overheads_base: Mapped[str] = mapped_column(
        String(30), nullable=False, default="direct_cost"
    )
    general_overheads_rate: Mapped[Decimal] = mapped_column(
        Amount, nullable=False, default=Decimal("0")
    )
    general_overheads_base: Mapped[str] = mapped_column(
        String(30), nullable=False, default="direct_plus_site"
    )
    contingency_rate: Mapped[Decimal] = mapped_column(Amount, nullable=False, default=Decimal("0"))
    contingency_base: Mapped[str] = mapped_column(
        String(30), nullable=False, default="running_total"
    )
    margin_rate: Mapped[Decimal] = mapped_column(Amount, nullable=False, default=Decimal("0"))
    margin_method: Mapped[str] = mapped_column(String(20), nullable=False, default="on_cost")

    missing_price_policy: Mapped[str] = mapped_column(String(10), nullable=False, default="block")
    quote_number_pattern: Mapped[str] = mapped_column(
        String(60), nullable=False, default="DEV-{year}-{sequence:04d}"
    )
    show_internal_costs_in_client_pdf: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )
    ai_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    organization: Mapped[Organization] = relationship(back_populates="settings")


class TaxRateRow(TimestampMixin, Base):
    __tablename__ = "tax_rates"
    __table_args__ = (
        UniqueConstraint("organization_id", "code", "applies_from", name="uq_tax_org_code_from"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    code: Mapped[str] = mapped_column(String(30), nullable=False)
    label: Mapped[str] = mapped_column(String(120), nullable=False)
    rate: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    applies_from: Mapped[datetime | None] = mapped_column(Date)
    applies_to: Mapped[datetime | None] = mapped_column(Date)
    is_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    source: Mapped[str | None] = mapped_column(String(255))


class User(TimestampMixin, Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    full_name: Mapped[str] = mapped_column(String(200), nullable=False)
    locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    memberships: Mapped[list[Membership]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class Membership(TimestampMixin, Base):
    """A user's role inside one organisation. A user may belong to several."""

    __tablename__ = "memberships"
    __table_args__ = (
        UniqueConstraint("user_id", "organization_id", name="uq_membership_user_org"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(String(40), nullable=False, default="estimator")
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    user: Mapped[User] = relationship(back_populates="memberships")


# --------------------------------------------------------------------------
# Country / region packs
# --------------------------------------------------------------------------


class RegionProfile(TimestampMixin, Base):
    """A versioned country/region pack.

    Global (not tenant-owned): the pack describes public rules, an organisation
    only *selects* one. ``terminology`` and ``rules`` stay JSON on purpose —
    what a pack needs to declare differs per country and must not require a
    migration for each new one.
    """

    __tablename__ = "region_profiles"
    __table_args__ = (UniqueConstraint("code", "version", name="uq_region_code_version"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    country_code: Mapped[str] = mapped_column(String(2), nullable=False, index=True)
    code: Mapped[str] = mapped_column(String(10), nullable=False)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    version: Mapped[str] = mapped_column(String(20), nullable=False, default="2026.1")
    effective_from: Mapped[datetime | None] = mapped_column(Date)
    default_locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    locales: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    default_currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    terminology: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    rules: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    sources: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    disclaimer: Mapped[str | None] = mapped_column(Text)


# --------------------------------------------------------------------------
# Projects
# --------------------------------------------------------------------------


class Project(TimestampMixin, Base):
    __tablename__ = "projects"
    __table_args__ = (
        UniqueConstraint("organization_id", "reference", name="uq_project_org_reference"),
        Index("ix_projects_org_status", "organization_id", "status"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    reference: Mapped[str] = mapped_column(String(60), nullable=False)
    client_reference: Mapped[str | None] = mapped_column(String(120))
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    client_name: Mapped[str | None] = mapped_column(String(200))
    address: Mapped[str | None] = mapped_column(String(255))
    postal_code: Mapped[str | None] = mapped_column(String(20))
    city: Mapped[str | None] = mapped_column(String(120))
    country_code: Mapped[str] = mapped_column(String(2), nullable=False, default="BE")
    region_code: Mapped[str] = mapped_column(String(10), nullable=False, default="BE-WAL")
    latitude: Mapped[Decimal | None] = mapped_column(Amount)
    longitude: Mapped[Decimal | None] = mapped_column(Amount)
    market_type: Mapped[str | None] = mapped_column(String(60))
    work_categories: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    submission_deadline: Mapped[datetime | None] = mapped_column(DateTime)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    locale: Mapped[str] = mapped_column(String(10), nullable=False, default="fr-BE")
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="draft")
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


# --------------------------------------------------------------------------
# Price library
# --------------------------------------------------------------------------


class PriceBook(TimestampMixin, Base):
    __tablename__ = "price_books"
    __table_args__ = (UniqueConstraint("organization_id", "name", name="uq_pricebook_org_name"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(160), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    is_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class PriceBookVersion(TimestampMixin, Base):
    """A published version is immutable; drafts are where imports land."""

    __tablename__ = "price_book_versions"
    __table_args__ = (
        UniqueConstraint("price_book_id", "version_number", name="uq_pbv_book_number"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("price_books.id", ondelete="CASCADE"), nullable=False, index=True
    )
    version_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    label: Mapped[str | None] = mapped_column(String(160))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    published_at: Mapped[datetime | None] = mapped_column(DateTime)
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


class PriceItem(TimestampMixin, Base):
    __tablename__ = "price_items"
    __table_args__ = (
        UniqueConstraint("price_book_version_id", "code", name="uq_priceitem_version_code"),
        Index("ix_price_items_org_family", "organization_id", "family"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("price_book_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    code: Mapped[str] = mapped_column(String(60), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    family: Mapped[str | None] = mapped_column(String(60))
    resource_kind: Mapped[str] = mapped_column(String(30), nullable=False, default="material")
    unit_code: Mapped[str] = mapped_column(String(12), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Amount, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    supplier_name: Mapped[str | None] = mapped_column(String(200))
    region_code: Mapped[str | None] = mapped_column(String(10))
    valid_from: Mapped[datetime | None] = mapped_column(Date)
    valid_to: Mapped[datetime | None] = mapped_column(Date)
    min_quantity: Mapped[Decimal | None] = mapped_column(Amount)
    lead_time_days: Mapped[int | None] = mapped_column(Integer)
    source: Mapped[str | None] = mapped_column(String(255))
    conditions: Mapped[str | None] = mapped_column(Text)
    indexation: Mapped[str | None] = mapped_column(String(120))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    confidence: Mapped[str] = mapped_column(String(20), nullable=False, default="declared")
    is_demo_data: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    notes: Mapped[str | None] = mapped_column(Text)


class CompositePriceRow(TimestampMixin, Base):
    """A reusable sub-detail (sous-détail de prix)."""

    __tablename__ = "composite_prices"
    __table_args__ = (
        UniqueConstraint("price_book_version_id", "code", name="uq_composite_version_code"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("price_book_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    code: Mapped[str] = mapped_column(String(60), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    unit_code: Mapped[str] = mapped_column(String(12), nullable=False)
    notes: Mapped[str | None] = mapped_column(Text)
    is_demo_data: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    components: Mapped[list[CompositeComponentRow]] = relationship(
        back_populates="composite",
        cascade="all, delete-orphan",
        order_by="CompositeComponentRow.sort_index",
    )


class CompositeComponentRow(TimestampMixin, Base):
    """One row of a sub-detail.

    A single wide table with nullable columns keyed by ``component_type`` keeps
    the sub-detail readable in one query. Which columns are required for which
    type is validated in :mod:`metreo_api.services.composites`, and the
    check constraint below stops an unknown type from being stored at all.
    """

    __tablename__ = "composite_components"
    __table_args__ = (
        CheckConstraint(
            "component_type IN ('consumption','output_rate','rotation','lump_sum')",
            name="ck_composite_component_type",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    composite_price_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("composite_prices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    sort_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    component_type: Mapped[str] = mapped_column(String(20), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    resource_kind: Mapped[str] = mapped_column(String(30), nullable=False, default="other")
    price_item_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("price_items.id", ondelete="SET NULL")
    )

    # consumption
    consumption: Mapped[Decimal | None] = mapped_column(Amount)
    resource_unit_code: Mapped[str | None] = mapped_column(String(12))
    unit_price: Mapped[Decimal | None] = mapped_column(Amount)
    loss_ratio: Mapped[Decimal | None] = mapped_column(Amount)
    convert_boq_quantity: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    density_value: Mapped[Decimal | None] = mapped_column(Amount)
    density_source: Mapped[str | None] = mapped_column(String(255))

    # output rate
    output_rate: Mapped[Decimal | None] = mapped_column(Amount)
    hourly_rate: Mapped[Decimal | None] = mapped_column(Amount)
    crew_size: Mapped[Decimal | None] = mapped_column(Amount)

    # rotation
    payload_value: Mapped[Decimal | None] = mapped_column(Amount)
    payload_unit_code: Mapped[str | None] = mapped_column(String(12))
    cost_per_rotation: Mapped[Decimal | None] = mapped_column(Amount)
    round_up: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    distance_km: Mapped[Decimal | None] = mapped_column(Amount)
    rate_per_km: Mapped[Decimal | None] = mapped_column(Amount)

    # lump sum
    lump_sum_amount: Mapped[Decimal | None] = mapped_column(Amount)

    composite: Mapped[CompositePriceRow] = relationship(back_populates="components")


# --------------------------------------------------------------------------
# CSV import staging
# --------------------------------------------------------------------------


class ImportBatch(TimestampMixin, Base):
    """A previewed import. Nothing reaches ``price_items`` before ``commit``."""

    __tablename__ = "import_batches"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("price_book_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="previewed")
    strategy: Mapped[str] = mapped_column(String(20), nullable=False, default="create")
    row_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    valid_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    error_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    duplicate_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    column_mapping: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    committed_at: Mapped[datetime | None] = mapped_column(DateTime)

    rows: Mapped[list[ImportBatchRow]] = relationship(
        back_populates="batch", cascade="all, delete-orphan", order_by="ImportBatchRow.line_number"
    )


class ImportBatchRow(Base):
    __tablename__ = "import_batch_rows"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    batch_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("import_batches.id", ondelete="CASCADE"), nullable=False, index=True
    )
    line_number: Mapped[int] = mapped_column(Integer, nullable=False)
    raw: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    normalized: Mapped[dict | None] = mapped_column(SAJSON)
    is_valid: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    is_duplicate: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    errors: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)

    batch: Mapped[ImportBatch] = relationship(back_populates="rows")


# --------------------------------------------------------------------------
# Bill of quantities
# --------------------------------------------------------------------------


class BillOfQuantities(TimestampMixin, Base):
    __tablename__ = "bills_of_quantities"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    source: Mapped[str] = mapped_column(String(20), nullable=False, default="manual")
    revision: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    notes: Mapped[str | None] = mapped_column(Text)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class BoqItem(TimestampMixin, Base):
    __tablename__ = "boq_items"
    __table_args__ = (
        UniqueConstraint("boq_id", "position", name="uq_boqitem_boq_position"),
        CheckConstraint(
            "kind IN ('section','item','option','variant','provisional')",
            name="ck_boq_item_kind",
        ),
        CheckConstraint(
            "status IN ('proposed','verified','approved','rejected')",
            name="ck_boq_item_status",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    boq_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("bills_of_quantities.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    parent_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("boq_items.id", ondelete="CASCADE")
    )
    sort_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    position: Mapped[str] = mapped_column(String(40), nullable=False)
    code: Mapped[str | None] = mapped_column(String(60))
    designation: Mapped[str] = mapped_column(Text, nullable=False)
    unit_code: Mapped[str] = mapped_column(String(12), nullable=False, default="fft")
    quantity: Mapped[Decimal] = mapped_column(Amount, nullable=False, default=Decimal("0"))
    kind: Mapped[str] = mapped_column(String(20), nullable=False, default="item")
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="proposed")
    formula: Mapped[str | None] = mapped_column(Text)
    client_quantity: Mapped[Decimal | None] = mapped_column(Amount)
    notes: Mapped[str | None] = mapped_column(Text)
    price_item_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("price_items.id", ondelete="SET NULL")
    )
    composite_price_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("composite_prices.id", ondelete="SET NULL")
    )


# --------------------------------------------------------------------------
# Estimates
# --------------------------------------------------------------------------


class Estimate(TimestampMixin, Base):
    __tablename__ = "estimates"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    boq_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("bills_of_quantities.id", ondelete="CASCADE"), nullable=False
    )
    price_book_version_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("price_book_versions.id"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="EUR")
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime)


class EstimateVersion(TimestampMixin, Base):
    """A frozen version stores the computed result *and* its inputs.

    ``snapshot`` holds the resolved lines, the price book version identifier,
    the markup policy and the tax rates that were in force. Recomputing it later
    reproduces the same numbers even if the library has moved on, which is what
    acceptance scenarios 6 and 7 require.
    """

    __tablename__ = "estimate_versions"
    __table_args__ = (
        UniqueConstraint("estimate_id", "version_number", name="uq_estimateversion_number"),
        CheckConstraint(
            "status IN ('draft','frozen','superseded')", name="ck_estimate_version_status"
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    estimate_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("estimates.id", ondelete="CASCADE"), nullable=False, index=True
    )
    version_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    label: Mapped[str | None] = mapped_column(String(200))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    price_book_version_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("price_book_versions.id"), nullable=False
    )
    markup: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    taxes: Mapped[list] = mapped_column(SAJSON, nullable=False, default=list)
    rounding: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    missing_price_policy: Mapped[str] = mapped_column(String(10), nullable=False, default="block")
    snapshot: Mapped[dict | None] = mapped_column(SAJSON)
    snapshot_sha256: Mapped[str | None] = mapped_column(String(64))
    total_selling_price_ht: Mapped[Decimal | None] = mapped_column(Amount)
    total_ttc: Mapped[Decimal | None] = mapped_column(Amount)
    frozen_at: Mapped[datetime | None] = mapped_column(DateTime)
    frozen_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))
    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id"))


# --------------------------------------------------------------------------
# Audit
# --------------------------------------------------------------------------


class AuditEvent(Base):
    """Append-only journal with a per-organisation hash chain.

    ``previous_hash`` links each row to the one before it inside the same
    organisation. Deleting or editing a row breaks the chain, which
    ``/audit/verify`` detects. This is tamper-evidence, not tamper-proofing —
    stated as such in the security threat model.
    """

    __tablename__ = "audit_events"
    __table_args__ = (
        Index("ix_audit_org_occurred", "organization_id", "occurred_at"),
        UniqueConstraint("organization_id", "sequence", name="uq_audit_org_sequence"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    organization_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    sequence: Mapped[int] = mapped_column(Integer, nullable=False)
    occurred_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=utcnow)
    actor_user_id: Mapped[str | None] = mapped_column(String(36))
    actor_email: Mapped[str | None] = mapped_column(String(255))
    action: Mapped[str] = mapped_column(String(80), nullable=False)
    object_type: Mapped[str] = mapped_column(String(60), nullable=False)
    object_id: Mapped[str | None] = mapped_column(String(36))
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[dict] = mapped_column(SAJSON, nullable=False, default=dict)
    request_id: Mapped[str | None] = mapped_column(String(64))
    #: Version du schéma de hash sous laquelle l'événement a été scellé. Une
    #: constante Python seule ne permettrait pas de revérifier durablement des
    #: événements créés sous plusieurs versions : la vérification lirait le code
    #: d'aujourd'hui pour juger un scellé d'hier.
    #: Renseigné explicitement par `audit.record()`. Pas de valeur par défaut :
    #: un défaut silencieux à 1 marquerait un événement scellé en v2 comme v1,
    #: et le rendrait invérifiable.
    hash_schema_version: Mapped[int] = mapped_column(Integer, nullable=False)
    previous_hash: Mapped[str | None] = mapped_column(String(64))
    hash: Mapped[str] = mapped_column(String(64), nullable=False)
